/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Controlador.Controladora;
import ClasesDocumentos.ClienteDoc;
import ClasesDocumentos.Documento;
import ClasesDocumentos.FacturaDoc;
import ClasesDocumentos.ImprecionPDF;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import proyectoferreteria.Cliente;
import proyectoferreteria.Factura;
import proyectoferreteria.Venta;


/**
 *
 * @author VícAlex
 */
public class menuCaja extends javax.swing.JFrame implements Runnable {
    
    private String  hora,minuto,segundo,ampm,dia,mes,anio;
    private Thread h1;
    
    private Documento Inventarioxml;
    private Controladora control;
    private ClienteDoc xmlListado;
    public Cliente comprador;
    public ArrayList<Venta>  ventas;
    public static ArrayList<Factura> facturas;
    private static FacturaDoc xmlFactura;

    public menuCaja() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        h1 = new Thread(this);
        h1.start();
        control =new Controladora();       
        Inventarioxml = new Documento();
        xmlListado = new ClienteDoc();
        ventas=new ArrayList<>();
        xmlFactura=new FacturaDoc();
        try {
            facturas=xmlFactura.elementToArray();
        } catch (ParseException ex) {
            Logger.getLogger(menuCaja.class.getName()).log(Level.SEVERE, null, ex);
        }
        fieldNroFactura.setText(Integer.toString(facturas.size()));
        
    }
    
    public menuCaja(ArrayList<Venta>  ventas) {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        h1 = new Thread(this);
        h1.start();
        control =new Controladora();       
        Inventarioxml = new Documento();
        xmlListado = new ClienteDoc();
        this.ventas=ventas;
        xmlFactura=new FacturaDoc();
        fieldNroFactura.setText(Integer.toString(facturas.size()));
        try {
            facturas=xmlFactura.elementToArray();
            } catch (ParseException ex) {
            Logger.getLogger(menuCaja.class.getName()).log(Level.SEVERE, null, ex);
        }
        
           
    }

    public JTable getTablaCaja() {
        return this.tablaCaja;
    }
    
    public void setModelTablaCaja(TableModel modelo){
        this.tablaCaja.setModel((DefaultTableModel) modelo);
        
        
    }
    
   
    

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        panel1 = new javax.swing.JPanel();
        panel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCaja = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        btnCargarVenta = new javax.swing.JPanel();
        txtVentasEspera = new javax.swing.JLabel();
        btnAlamacenar = new javax.swing.JPanel();
        txtAlmacenar = new javax.swing.JLabel();
        btnregresar = new javax.swing.JPanel();
        txtCancelar = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        fieldTotalPagar = new javax.swing.JTextField();
        fieldIVA = new javax.swing.JTextField();
        fieldSubTotal = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnEliminar = new javax.swing.JPanel();
        txtEliminar = new javax.swing.JLabel();
        btnArticulo = new javax.swing.JPanel();
        txtAgregarArticulo = new javax.swing.JLabel();
        btnImprimir = new javax.swing.JPanel();
        txtFacturar = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnAgregarCliente = new javax.swing.JPanel();
        txtAgregar = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JPanel();
        txtGuardar = new javax.swing.JLabel();
        fieldCI = new javax.swing.JTextField();
        fieldNombre = new javax.swing.JTextField();
        fieldDireccion = new javax.swing.JTextField();
        fieldTelefono = new javax.swing.JTextField();
        comboNacional = new javax.swing.JComboBox<>();
        txtNombre = new javax.swing.JLabel();
        txtCIRIF = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JLabel();
        txtNroFActura = new javax.swing.JLabel();
        fieldNroFactura = new javax.swing.JTextField();
        fechaActual = new com.toedter.calendar.JDateChooser();
        txtFEchaEmision = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txtReloj = new javax.swing.JLabel();
        txtFecha = new javax.swing.JLabel();
        txtInventario = new javax.swing.JLabel();
        txtLocal = new javax.swing.JLabel();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        panel1.setBackground(new java.awt.Color(16, 135, 60));

        panel2.setBackground(new java.awt.Color(10, 91, 40));
        panel2.setAlignmentX(1.0F);
        panel2.setAlignmentY(1.0F);

        tablaCaja.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tablaCaja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Codigo", "Descripcion", "Unidades", "IVA %", "Precio  Unidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaCaja.setToolTipText("");
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(JLabel.RIGHT);
        tablaCaja.getColumnModel().getColumn(4).setCellRenderer(rightRenderer);
        tablaCaja.getColumnModel().getColumn(5).setCellRenderer(rightRenderer);
        tablaCaja.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tablaCajaFocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(tablaCaja);
        if (tablaCaja.getColumnModel().getColumnCount() > 0) {
            tablaCaja.getColumnModel().getColumn(0).setPreferredWidth(75);
            tablaCaja.getColumnModel().getColumn(1).setPreferredWidth(50);
            tablaCaja.getColumnModel().getColumn(2).setPreferredWidth(200);
            tablaCaja.getColumnModel().getColumn(4).setPreferredWidth(40);
            tablaCaja.getColumnModel().getColumn(5).setPreferredWidth(50);
        }
        tablaCaja.getColumnModel().getColumn(0).setPreferredWidth(75);
        tablaCaja.getColumnModel().getColumn(1).setPreferredWidth(10);
        tablaCaja.getColumnModel().getColumn(2).setPreferredWidth(150);
        tablaCaja.getColumnModel().getColumn(3).setPreferredWidth(10);
        tablaCaja.getColumnModel().getColumn(4).setPreferredWidth(30);
        tablaCaja.getColumnModel().getColumn(5).setPreferredWidth(100);

        jPanel1.setBackground(new java.awt.Color(10, 91, 40));
        jPanel1.setToolTipText("");

        btnCargarVenta.setBackground(new java.awt.Color(16, 135, 61));
        btnCargarVenta.setPreferredSize(new java.awt.Dimension(96, 34));
        btnCargarVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCargarVentaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCargarVentaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCargarVentaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnCargarVentaMouseReleased(evt);
            }
        });
        btnCargarVenta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtVentasEspera.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtVentasEspera.setForeground(new java.awt.Color(255, 255, 255));
        txtVentasEspera.setText("Cargar Venta");
        btnCargarVenta.add(txtVentasEspera, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 110, 30));

        btnAlamacenar.setBackground(new java.awt.Color(16, 135, 61));
        btnAlamacenar.setPreferredSize(new java.awt.Dimension(96, 34));
        btnAlamacenar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAlamacenarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAlamacenarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAlamacenarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnAlamacenarMouseReleased(evt);
            }
        });
        btnAlamacenar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtAlmacenar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtAlmacenar.setForeground(new java.awt.Color(255, 255, 255));
        txtAlmacenar.setText("Poner en Espera");
        btnAlamacenar.add(txtAlmacenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 130, 30));

        btnregresar.setBackground(new java.awt.Color(16, 135, 61));
        btnregresar.setPreferredSize(new java.awt.Dimension(96, 34));
        btnregresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnregresarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnregresarMouseReleased(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnregresarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnregresarMouseEntered(evt);
            }
        });
        btnregresar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCancelar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtCancelar.setForeground(new java.awt.Color(255, 255, 255));
        txtCancelar.setText(" Cancelar");
        btnregresar.add(txtCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 80, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnCargarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAlamacenar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnregresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCargarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnAlamacenar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnregresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel2.setBackground(new java.awt.Color(10, 91, 40));

        jLabel28.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Bs.");

        jLabel27.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Bs.");

        jLabel26.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Bs.");

        fieldTotalPagar.setBackground(new java.awt.Color(16, 135, 61));
        fieldTotalPagar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        fieldTotalPagar.setForeground(new java.awt.Color(255, 255, 255));
        fieldTotalPagar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        fieldTotalPagar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(35, 155, 81)));
        fieldTotalPagar.setCaretColor(new java.awt.Color(255, 255, 255));
        fieldTotalPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldTotalPagarActionPerformed(evt);
            }
        });

        fieldIVA.setBackground(new java.awt.Color(16, 135, 61));
        fieldIVA.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        fieldIVA.setForeground(new java.awt.Color(255, 255, 255));
        fieldIVA.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        fieldIVA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(35, 155, 81)));
        fieldIVA.setCaretColor(new java.awt.Color(255, 255, 255));
        fieldIVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldIVAActionPerformed(evt);
            }
        });

        fieldSubTotal.setBackground(new java.awt.Color(16, 135, 61));
        fieldSubTotal.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        fieldSubTotal.setForeground(new java.awt.Color(255, 255, 255));
        fieldSubTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        fieldSubTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(35, 155, 81)));
        fieldSubTotal.setCaretColor(new java.awt.Color(255, 255, 255));
        fieldSubTotal.setEnabled(false);

        jLabel24.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Sub Total:");

        jLabel25.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("I.V.A.:");

        jLabel17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Total:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel28))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel25)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(fieldIVA, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel27))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel17)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(fieldTotalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel26)))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(fieldTotalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24)
                            .addComponent(jLabel28))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(fieldIVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27))))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(10, 91, 40));

        btnEliminar.setBackground(new java.awt.Color(16, 135, 61));
        btnEliminar.setPreferredSize(new java.awt.Dimension(96, 34));
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEliminarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnEliminarMouseReleased(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarMouseEntered(evt);
            }
        });
        btnEliminar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtEliminar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtEliminar.setForeground(new java.awt.Color(255, 255, 255));
        txtEliminar.setText("Eliminar");
        txtEliminar.setEnabled(false);
        btnEliminar.add(txtEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 70, 30));

        btnArticulo.setBackground(new java.awt.Color(16, 135, 61));
        btnArticulo.setPreferredSize(new java.awt.Dimension(96, 34));
        btnArticulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnArticuloMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnArticuloMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnArticuloMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnArticuloMouseReleased(evt);
            }
        });
        btnArticulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtAgregarArticulo.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtAgregarArticulo.setForeground(new java.awt.Color(255, 255, 255));
        txtAgregarArticulo.setText("Agregar");
        btnArticulo.add(txtAgregarArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 70, 30));

        btnImprimir.setBackground(new java.awt.Color(16, 135, 61));
        btnImprimir.setPreferredSize(new java.awt.Dimension(96, 34));
        btnImprimir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnImprimirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnImprimirMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnImprimirMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnImprimirMouseReleased(evt);
            }
        });
        btnImprimir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtFacturar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtFacturar.setForeground(new java.awt.Color(255, 255, 255));
        txtFacturar.setText("Facturar");
        btnImprimir.add(txtFacturar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 70, 30));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4.setBackground(new java.awt.Color(10, 91, 40));

        btnAgregarCliente.setBackground(new java.awt.Color(16, 135, 61));
        btnAgregarCliente.setPreferredSize(new java.awt.Dimension(96, 34));
        btnAgregarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgregarClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgregarClienteMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAgregarClienteMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnAgregarClienteMouseReleased(evt);
            }
        });
        btnAgregarCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtAgregar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtAgregar.setForeground(new java.awt.Color(255, 255, 255));
        txtAgregar.setText("Agregar ");
        btnAgregarCliente.add(txtAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 70, 30));

        btnGuardar.setBackground(new java.awt.Color(16, 135, 61));
        btnGuardar.setEnabled(false);
        btnGuardar.setPreferredSize(new java.awt.Dimension(96, 34));
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGuardarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnGuardarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnGuardarMouseReleased(evt);
            }
        });
        btnGuardar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtGuardar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtGuardar.setForeground(new java.awt.Color(255, 255, 255));
        txtGuardar.setText("Guardar");
        btnGuardar.add(txtGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 70, 30));

        fieldCI.setBackground(new java.awt.Color(16, 135, 61));
        fieldCI.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        fieldCI.setForeground(new java.awt.Color(255, 255, 255));
        fieldCI.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(35, 155, 81)));
        fieldCI.setCaretColor(new java.awt.Color(255, 255, 255));
        fieldCI.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        fieldCI.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldCIFocusLost(evt);
            }
        });
        fieldCI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldCIKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fieldCIKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fieldCIKeyReleased(evt);
            }
        });

        fieldNombre.setBackground(new java.awt.Color(16, 135, 61));
        fieldNombre.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        fieldNombre.setForeground(new java.awt.Color(255, 255, 255));
        fieldNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(35, 155, 81)));
        fieldNombre.setCaretColor(new java.awt.Color(255, 255, 255));
        fieldNombre.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        fieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNombreActionPerformed(evt);
            }
        });
        fieldNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldNombreKeyTyped(evt);
            }
        });

        fieldDireccion.setBackground(new java.awt.Color(16, 135, 61));
        fieldDireccion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        fieldDireccion.setForeground(new java.awt.Color(255, 255, 255));
        fieldDireccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(35, 155, 81)));
        fieldDireccion.setCaretColor(new java.awt.Color(255, 255, 255));
        fieldDireccion.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        fieldDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldDireccionActionPerformed(evt);
            }
        });
        fieldDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldDireccionKeyTyped(evt);
            }
        });

        fieldTelefono.setBackground(new java.awt.Color(16, 135, 61));
        fieldTelefono.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        fieldTelefono.setForeground(new java.awt.Color(255, 255, 255));
        fieldTelefono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(35, 155, 81)));
        fieldTelefono.setCaretColor(new java.awt.Color(255, 255, 255));
        fieldTelefono.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        fieldTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldTelefonoActionPerformed(evt);
            }
        });
        fieldTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldTelefonoKeyTyped(evt);
            }
        });

        comboNacional.setBackground(new java.awt.Color(16, 135, 61));
        comboNacional.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "V", "E", "J" }));
        comboNacional.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                comboNacionalFocusLost(evt);
            }
        });
        comboNacional.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                comboNacionalMouseReleased(evt);
            }
        });
        comboNacional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboNacionalActionPerformed(evt);
            }
        });

        txtNombre.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(255, 255, 255));
        txtNombre.setText("CI/RIF:");

        txtCIRIF.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtCIRIF.setForeground(new java.awt.Color(255, 255, 255));
        txtCIRIF.setText("Cliente:");

        txtDireccion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtDireccion.setForeground(new java.awt.Color(255, 255, 255));
        txtDireccion.setText("Direccion:");

        txtTelefono.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtTelefono.setForeground(new java.awt.Color(255, 255, 255));
        txtTelefono.setText("Telefono:");

        txtNroFActura.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtNroFActura.setForeground(new java.awt.Color(255, 255, 255));
        txtNroFActura.setText("Nro. Factura:");

        fieldNroFactura.setBackground(new java.awt.Color(16, 135, 61));
        fieldNroFactura.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        fieldNroFactura.setForeground(new java.awt.Color(255, 255, 255));
        fieldNroFactura.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        fieldNroFactura.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(35, 155, 81)));
        fieldNroFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNroFacturaActionPerformed(evt);
            }
        });

        fechaActual.setBackground(new java.awt.Color(16, 135, 61));

        txtFEchaEmision.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtFEchaEmision.setForeground(new java.awt.Color(255, 255, 255));
        txtFEchaEmision.setText("Fecha Emision:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTelefono)
                    .addComponent(txtDireccion)
                    .addComponent(txtCIRIF)
                    .addComponent(txtNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fieldDireccion, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldTelefono, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(comboNacional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldCI, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE))
                    .addComponent(fieldNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAgregarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFEchaEmision, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNroFActura, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fechaActual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fieldNroFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldCI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre)
                            .addComponent(comboNacional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCIRIF))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDireccion)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnAgregarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefono)
                    .addComponent(fieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(fechaActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldNroFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNroFActura)))
            .addComponent(txtFEchaEmision)
        );

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3)
            .addComponent(jSeparator2)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane1)
                        .addGap(18, 18, 18)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(21, 21, 21))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        txtReloj.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtReloj.setForeground(new java.awt.Color(255, 255, 255));
        txtReloj.setText("Reloj");

        txtFecha.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtFecha.setForeground(new java.awt.Color(255, 255, 255));
        txtFecha.setText("Fecha");

        txtInventario.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        txtInventario.setForeground(new java.awt.Color(255, 255, 255));
        txtInventario.setText("Caja");

        txtLocal.setFont(new java.awt.Font("Arial Black", 2, 24)); // NOI18N
        txtLocal.setForeground(new java.awt.Color(255, 255, 255));
        txtLocal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ultrpequeño-05.png"))); // NOI18N
        txtLocal.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 2, new java.awt.Color(10, 91, 40)));

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtInventario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtFecha)
                .addGap(18, 18, 18)
                .addComponent(txtReloj)
                .addGap(21, 21, 21))
            .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFecha)
                            .addComponent(txtReloj)
                            .addComponent(txtInventario)))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCargarVentaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCargarVentaMouseReleased
        // cuando se suelta el boton
        // Aqui se ejecuta el codigo del boton
        
        btnCargarVenta.setBorder(BorderFactory.createMatteBorder(2, 2, 2, 2,Color.getHSBColor(143, 30, 77)));
        menuCargaVentaEspera obj = new menuCargaVentaEspera(this,ventas);
        obj.setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_btnCargarVentaMouseReleased

    private void btnCargarVentaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCargarVentaMousePressed
        // cuando se presiona el boton
        btnCargarVenta.setBorder(null);
    }//GEN-LAST:event_btnCargarVentaMousePressed

    private void btnCargarVentaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCargarVentaMouseExited
        // cuando el raton sale del boton
        btnCargarVenta.setBorder(null);
    }//GEN-LAST:event_btnCargarVentaMouseExited

    private void btnCargarVentaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCargarVentaMouseEntered
        //crea el borde del "boton"
        btnCargarVenta.setBorder(BorderFactory.createMatteBorder(2, 2, 2, 2,Color.getHSBColor(143, 30, 77)));
    }//GEN-LAST:event_btnCargarVentaMouseEntered

    private void btnEliminarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseReleased
        // cuando se suelta el boton
        // Aqui se ejecuta el codigo del boton
        if (txtEliminar.isEnabled()){
            DefaultTableModel dtm=((DefaultTableModel)tablaCaja.getModel()); dtm.removeRow(tablaCaja.getSelectedRow());
            tablaCaja.setModel(dtm);
            try {
                setPrecios();
            } catch (ParseException ex) {
                Logger.getLogger(menuCaja.class.getName()).log(Level.SEVERE, null, ex);
            }
            btnEliminar.setBorder(BorderFactory.createMatteBorder(2, 2, 2, 2,Color.getHSBColor(143, 30, 77)));
            txtEliminar.setEnabled(false);
            txtEliminar.requestFocus();
        }
    }//GEN-LAST:event_btnEliminarMouseReleased

    private void btnEliminarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMousePressed
        // cuando se presiona el boton
        btnEliminar.setBorder(null);
    }//GEN-LAST:event_btnEliminarMousePressed

    private void btnEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseExited
        // cuando el raton sale del boton
        btnEliminar.setBorder(null);
    }//GEN-LAST:event_btnEliminarMouseExited

    private void btnEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseEntered
        //crea el borde del "boton"
        if (txtEliminar.isEnabled())
        btnEliminar.setBorder(BorderFactory.createMatteBorder(2, 2, 2, 2,Color.getHSBColor(143, 30, 77)));
    }//GEN-LAST:event_btnEliminarMouseEntered

    private void fieldNroFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNroFacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNroFacturaActionPerformed

    private void btnArticuloMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnArticuloMouseReleased
        // cuando se suelta el boton
        // Aqui se ejecuta el codigo del boton
        btnArticulo.setBorder(BorderFactory.createMatteBorder(2, 2, 2, 2,Color.getHSBColor(143, 30, 77)));
        menuBuscarArticulo obj =new menuBuscarArticulo(this);
        obj.setVisible(true);
        this.setEnabled(false);

    }//GEN-LAST:event_btnArticuloMouseReleased

    private void btnArticuloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnArticuloMousePressed
        // cuando se presiona el boton
        btnArticulo.setBorder(null);
    }//GEN-LAST:event_btnArticuloMousePressed

    private void btnArticuloMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnArticuloMouseExited
        // cuando el raton sale del boton
        btnArticulo.setBorder(null);
    }//GEN-LAST:event_btnArticuloMouseExited

    private void btnArticuloMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnArticuloMouseEntered
        //crea el borde del "boton"
        btnArticulo.setBorder(BorderFactory.createMatteBorder(2, 2, 2, 2,Color.getHSBColor(143, 30, 77)));
    }//GEN-LAST:event_btnArticuloMouseEntered

    private void fieldIVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldIVAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldIVAActionPerformed

    private void fieldTotalPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldTotalPagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldTotalPagarActionPerformed

    private void btnAlamacenarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlamacenarMouseReleased
        // cuando se suelta el boton
        // Aqui se ejecuta el codigo del boton
        if(comboNacional.getSelectedIndex() != 0 && !"".equals(fieldCI.getText())&&
           !"".equals(fieldNombre.getText()) && !"".equals(fieldDireccion.getText()) &&
           !"".equals(fieldTelefono.getText()) && tablaCaja.getRowCount()!=0  ){
        btnAlamacenar.setBorder(BorderFactory.createMatteBorder(2, 2, 2, 2,Color.getHSBColor(143, 30, 77)));
        DefaultTableModel dtm = (DefaultTableModel)tablaCaja.getModel();
        ventas.add(new Venta(control.copyTableModel(dtm),comprador));
        
        JOptionPane.showMessageDialog(null, "Se ha guardado la venta exitosamente");
            try {
                cleanAll();
            } catch (ParseException ex) {
                Logger.getLogger(menuCaja.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else
            JOptionPane.showMessageDialog(null, "Existen Campos Vacios","Advertencia",2);
        
    }//GEN-LAST:event_btnAlamacenarMouseReleased

    private void btnAlamacenarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlamacenarMousePressed
        // cuando se presiona el boton
        btnAlamacenar.setBorder(null);
    }//GEN-LAST:event_btnAlamacenarMousePressed

    private void btnAlamacenarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlamacenarMouseExited
        // cuando el raton sale del boton
        btnAlamacenar.setBorder(null);
    }//GEN-LAST:event_btnAlamacenarMouseExited

    private void btnAlamacenarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlamacenarMouseEntered
        //crea el borde del "boton"
        btnAlamacenar.setBorder(BorderFactory.createMatteBorder(2, 2, 2, 2,Color.getHSBColor(143, 30, 77)));
    }//GEN-LAST:event_btnAlamacenarMouseEntered

    private void btnImprimirMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImprimirMouseReleased
        // cuando se suelta el boton
        // Aqui se ejecuta el codigo del boton
        //tablaCaja.clearSelection();
        if(comboNacional.getSelectedIndex() != 0 && !"".equals(fieldCI.getText())&&
           !"".equals(fieldNombre.getText()) && !"".equals(fieldDireccion.getText()) &&
           !"".equals(fieldTelefono.getText()) && tablaCaja.getRowCount()!=0  ){
           Factura e = null; 
           if  (fechaActual.getCalendar() !=null){
               try {
                   e= new Factura(fechaActual.getCalendar(),control.parseToFloat(fieldTotalPagar.getText()),
                           control.parseToFloat(fieldIVA.getText()),control.parseToFloat(fieldSubTotal.getText()),facturas.size());
                   facturas.add(e);
                   xmlFactura.arrayToElement(facturas);
                   fieldNroFactura.setText(Integer.toString(facturas.size()));
                   setVendido();
                   JOptionPane.showMessageDialog(null, "Facturacion Completada Exitosamente");
                   setFieldsCliente("","","","");
                   
               } catch (ParseException ex) {
                   
                   Logger.getLogger(menuCaja.class.getName()).log(Level.SEVERE, null, ex);
                   
               }
                                    
           }
           else{
               
               try {
                   e= new Factura(Calendar.getInstance(),control.parseToFloat(fieldTotalPagar.getText()),
                           control.parseToFloat(fieldIVA.getText()),control.parseToFloat(fieldSubTotal.getText()),facturas.size());
                   facturas.add(e);
                   xmlFactura.arrayToElement(facturas);
                   fieldNroFactura.setText(Integer.toString(facturas.size()));
                   setVendido();
                   JOptionPane.showMessageDialog(null, "Facturacion Completada Exitosamente");
                   
                   
             
               } catch (ParseException ex) {
                   
                   Logger.getLogger(menuCaja.class.getName()).log(Level.SEVERE, null, ex);
                   
               }
                                
               
           }
           ImprecionPDF facturar = new ImprecionPDF("factura-Nro" + Integer.toString(facturas.size()-1));
            try {
                facturar.crearFactura(e, tablaCaja, facturas.size()-1);
                cleanAll(); 
            } catch (ParseException ex) {
                Logger.getLogger(menuCaja.class.getName()).log(Level.SEVERE, null, ex);
            }
          
        }
        else {
            JOptionPane.showMessageDialog(null, "Error, hay campos vacios","Advertencia",2);
        }
        btnImprimir.setBorder(BorderFactory.createMatteBorder(2, 2, 2, 2,Color.getHSBColor(143, 30, 77)));
    }//GEN-LAST:event_btnImprimirMouseReleased

    private void btnImprimirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImprimirMousePressed
        // cuando se presiona el boton
        btnImprimir.setBorder(null);
    }//GEN-LAST:event_btnImprimirMousePressed

    private void btnImprimirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImprimirMouseExited
        // cuando el raton sale del boton
        btnImprimir.setBorder(null);
    }//GEN-LAST:event_btnImprimirMouseExited

    private void btnImprimirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImprimirMouseEntered
        //crea el borde del "boton"
        btnImprimir.setBorder(BorderFactory.createMatteBorder(2, 2, 2, 2,Color.getHSBColor(143, 30, 77)));
    }//GEN-LAST:event_btnImprimirMouseEntered

    private void tablaCajaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tablaCajaFocusGained
        // TODO add your handling code here:
        if (tablaCaja.getSelectedRow()!= -1)
            txtEliminar.setEnabled(true);

    }//GEN-LAST:event_tablaCajaFocusGained

    private void btnregresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnregresarMouseEntered
        //crea el borde del "boton"
        btnregresar.setBorder(BorderFactory.createMatteBorder(2, 2, 2, 2,Color.getHSBColor(143, 30, 77)));
    }//GEN-LAST:event_btnregresarMouseEntered

    private void btnregresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnregresarMouseExited
        // cuando el raton sale del boton
        btnregresar.setBorder(null);
    }//GEN-LAST:event_btnregresarMouseExited

    private void btnregresarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnregresarMouseReleased
        // cuando se suelta el boton
        // Aqui se ejecuta el codigo del boton
        btnregresar.setBorder(BorderFactory.createMatteBorder(2, 2, 2, 2,Color.getHSBColor(143, 30, 77)));
        menuEntrada obj = new menuEntrada(ventas);
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnregresarMouseReleased

    private void btnregresarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnregresarMousePressed
        // cuando se presiona el boton
        btnregresar.setBorder(null);
    }//GEN-LAST:event_btnregresarMousePressed

    private void comboNacionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboNacionalActionPerformed
      /*  
        if(comboNacional.getSelectedIndex() != 0 && !"".equals(fieldCI.getText()) && !ClienteAgregado ){
            Cliente persona = null;
            persona = xmlListado.buscarClienet(fieldCI.getText(),
                                             (String)comboNacional.getSelectedItem());
            if(persona != null && !ClienteAgregado){
                int confirmacion = JOptionPane.showOptionDialog(
                        null,"¿Se encontraron datos de un cliente registrado \n"
                                + " desea agregar a "+persona.getNombre()+"?", "::::...Confirmación...:::",
                        JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,null,null);
                if (confirmacion==0) {
                    ClienteAgregado = true;
                    fieldCI.setEnabled(false);
                    btnGuardar.setEnabled(false);
                    txtGuardar.setEnabled(false);
                    setFieldsCliente(persona.getNombre(),persona.getDocumento(),persona.getDireccion(),persona.getTelefono());
                }    
            } 
        }
        */
    }//GEN-LAST:event_comboNacionalActionPerformed

    private void fieldTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldTelefonoKeyTyped
        // TODO add your handling code here:
        control.validaNumero(evt);
    }//GEN-LAST:event_fieldTelefonoKeyTyped

    private void fieldTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldTelefonoActionPerformed

    private void fieldDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldDireccionActionPerformed

    private void fieldNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldNombreKeyTyped
     control.validaLetra(evt);
    }//GEN-LAST:event_fieldNombreKeyTyped

    private void fieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNombreActionPerformed

    private void fieldCIKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldCIKeyReleased
        // TODO add your handling code here:
       /* 
        if(comboNacional.getSelectedIndex() != 0 && !"".equals(fieldCI.getText()) && !ClienteAgregado ){
           Cliente persona = null;
           persona = xmlListado.buscarClienet(fieldCI.getText(),
                                             (String)comboNacional.getSelectedItem());
            if(persona != null && !ClienteAgregado){
                int confirmacion = JOptionPane.showOptionDialog(
                        null,"¿Se encontraron datos de un cliente registrado \n"
                                + " desea agregar a "+persona.getNombre()+"?", "::::...Confirmación...:::",
                        JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,null,null);
                if (confirmacion==0) {
                    ClienteAgregado = true;
                    btnGuardar.setEnabled(false);
                    txtGuardar.setEnabled(false);
                    fieldCI.setEnabled(false);
                    setFieldsCliente(persona.getNombre(),persona.getDocumento(),persona.getDireccion(),persona.getTelefono());
                }    
            } 
        }*/
           
    }//GEN-LAST:event_fieldCIKeyReleased

    private void fieldCIFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldCIFocusLost
        // TODO add your handling code here:
        if(xmlListado.buscarCliente(fieldCI.getText())!=null){
            Cliente e=xmlListado.buscarCliente(fieldCI.getText());
            setFieldsCliente(e.getNombre(),e.getDocumento(),e.getDireccion(),e.getTelefono());
            comprador=e;  
            txtGuardar.setText("Eliminar");
            
        }
            
    }//GEN-LAST:event_fieldCIFocusLost

    private void btnGuardarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseReleased
        if (txtGuardar.getText().equals("Eliminar")){
            setFieldsCliente("","","","");
            txtGuardar.setText("Guardar");
            
        }
        else{
        if(comboNacional.getSelectedIndex() != 0 && !"".equals(fieldCI.getText())&& xmlListado.buscarClienet(fieldCI.getText(), comboNacional.getSelectedItem().toString())!=null){
            Cliente e=xmlListado.buscarClienet(fieldCI.getText(), comboNacional.getSelectedItem().toString());
            setFieldsCliente(e.getNombre(),e.getDocumento(),e.getDireccion(),e.getTelefono());
            comprador=e;
            JOptionPane.showMessageDialog(null, "Cliente ya resgistrado, si desea modificarlo dirijase al menu Registro Clientes");
            txtGuardar.setText("Eliminar");
        }
            
            
        if(txtGuardar.isEnabled()&& txtGuardar.getText().equals("Guardar")){
        if(comboNacional.getSelectedIndex() != 0 && !"".equals(fieldCI.getText())&&
           !"".equals(fieldNombre.getText()) && !"".equals(fieldDireccion.getText()) &&
           !"".equals(fieldTelefono.getText()) ){
                int confirmacion = JOptionPane.showOptionDialog(
                       null,"¿Seguro que quiere guardar los datos de este cliente?", "::::...Confirmación...:::",
                       JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,null,null);
                if (confirmacion==0){
                    Cliente persona = new Cliente();
                    persona.setNombre(fieldNombre.getText());
                    persona.setDocumento((String)comboNacional.getSelectedItem()+"-"+fieldCI.getText());
                    persona.setDireccion(fieldDireccion.getText());
                    persona.setTelefono(fieldTelefono.getText());
                    txtGuardar.setText("Eliminar");
                    xmlListado.guardarDatosCliente(persona);
                    comprador=persona;
                }
        }
        else
            JOptionPane.showMessageDialog(null, "Error, hay campos vacios","advertencia",2);
        }
        }
        //txtGuardar.setEnabled(true);
    }//GEN-LAST:event_btnGuardarMouseReleased

    private void btnGuardarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMousePressed
        // cuando se presiona el boton
        btnGuardar.setBorder(null);
    }//GEN-LAST:event_btnGuardarMousePressed

    private void btnGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseExited
        // cuando el raton sale del boton
        btnGuardar.setBorder(null);
    }//GEN-LAST:event_btnGuardarMouseExited

    private void btnGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseEntered
        //crea el borde del "boton"
        if(txtGuardar.isEnabled())
        btnGuardar.setBorder(BorderFactory.createMatteBorder(2, 2, 2, 2,Color.getHSBColor(143, 30, 77)));
    }//GEN-LAST:event_btnGuardarMouseEntered

    private void btnAgregarClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarClienteMouseEntered
        //crea el borde del "boton"
        btnAgregarCliente.setBorder(BorderFactory.createMatteBorder(2, 2, 2, 2,Color.getHSBColor(143, 30, 77)));
    }//GEN-LAST:event_btnAgregarClienteMouseEntered

    private void btnAgregarClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarClienteMouseExited
        // cuando el raton sale del boton
        btnAgregarCliente.setBorder(null);
    }//GEN-LAST:event_btnAgregarClienteMouseExited

    private void btnAgregarClienteMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarClienteMouseReleased
        // cuando se suelta el boton
        // Aqui se ejecuta el codigo del boton
        btnAgregarCliente.setBorder(BorderFactory.createMatteBorder(2, 2, 2, 2,Color.getHSBColor(143, 30, 77)));     
        menuCliente obj = new menuCliente(xmlListado,this);
        obj.setVisible(true);
        //setFields(persona.getNombre(),persona.getDocumento(),persona.getDireccion(), persona.getTelefono());
    }//GEN-LAST:event_btnAgregarClienteMouseReleased

    private void btnAgregarClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarClienteMousePressed
        // cuando se presiona el boton
        btnAgregarCliente.setBorder(null);
    }//GEN-LAST:event_btnAgregarClienteMousePressed

    private void fieldCIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldCIKeyTyped
        // TODO add your handling code here:
        
        
        control.validaNumero(evt);
    }//GEN-LAST:event_fieldCIKeyTyped

    private void fieldDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldDireccionKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldDireccionKeyTyped

    private void comboNacionalMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboNacionalMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_comboNacionalMouseReleased

    private void comboNacionalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_comboNacionalFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_comboNacionalFocusLost

    private void fieldCIKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldCIKeyPressed
        // TODO add your handling code here:
        if(KeyEvent.VK_ENTER==evt.getKeyCode()&&xmlListado.buscarCliente(fieldCI.getText())!=null){
            Cliente e=xmlListado.buscarCliente(fieldCI.getText());
            setFieldsCliente(e.getNombre(),e.getDocumento(),e.getDireccion(),e.getTelefono());
            comprador=e;  
            txtGuardar.setText("Eliminar");
        }
    }//GEN-LAST:event_fieldCIKeyPressed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuCaja().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnAgregarCliente;
    private javax.swing.JPanel btnAlamacenar;
    private javax.swing.JPanel btnArticulo;
    private javax.swing.JPanel btnCargarVenta;
    private javax.swing.JPanel btnEliminar;
    private javax.swing.JPanel btnGuardar;
    private javax.swing.JPanel btnImprimir;
    private javax.swing.JPanel btnregresar;
    private javax.swing.JComboBox<String> comboNacional;
    private com.toedter.calendar.JDateChooser fechaActual;
    private javax.swing.JTextField fieldCI;
    private javax.swing.JTextField fieldDireccion;
    private javax.swing.JTextField fieldIVA;
    private javax.swing.JTextField fieldNombre;
    private javax.swing.JTextField fieldNroFactura;
    private javax.swing.JTextField fieldSubTotal;
    private javax.swing.JTextField fieldTelefono;
    private javax.swing.JTextField fieldTotalPagar;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JTable tablaCaja;
    private javax.swing.JLabel txtAgregar;
    private javax.swing.JLabel txtAgregarArticulo;
    private javax.swing.JLabel txtAlmacenar;
    private javax.swing.JLabel txtCIRIF;
    private javax.swing.JLabel txtCancelar;
    private javax.swing.JLabel txtDireccion;
    private javax.swing.JLabel txtEliminar;
    private javax.swing.JLabel txtFEchaEmision;
    private javax.swing.JLabel txtFacturar;
    private javax.swing.JLabel txtFecha;
    public javax.swing.JLabel txtGuardar;
    private javax.swing.JLabel txtInventario;
    private javax.swing.JLabel txtLocal;
    private javax.swing.JLabel txtNombre;
    private javax.swing.JLabel txtNroFActura;
    private javax.swing.JLabel txtReloj;
    private javax.swing.JLabel txtTelefono;
    private javax.swing.JLabel txtVentasEspera;
    // End of variables declaration//GEN-END:variables

@Override
    public void run() {
        Thread ct = Thread.currentThread();
        
        while(ct == h1){
            calcula();
            txtReloj.setText("Hora: "+hora+":"+minuto+":"+segundo+" "+ampm);
            txtFecha.setText("Fecha: "+dia+"/"+mes+"/"+anio);
            try{
                Thread.sleep(1000); 
                }
            catch(InterruptedException e){
            
            }
        }

    }
    
    private void calcula() {
        Calendar calendario = new GregorianCalendar();
        mes=(String) String.valueOf(calendario.get(Calendar.MONTH)+1);
        anio=(String) String.valueOf(calendario.get(Calendar.YEAR));
        dia=(String) String.valueOf(calendario.get(Calendar.DAY_OF_MONTH));
        ampm = calendario.get(Calendar.AM_PM) == calendario.AM?"AM":"PM";
        
        if(ampm.equals("PM")){
            int h = calendario.get(calendario.HOUR_OF_DAY)-12;
            h = h == 0?12:h;
            hora = h>9?""+h:"0"+h;
        }else{
            hora = calendario.get(calendario.HOUR_OF_DAY)>9?""+calendario.get(calendario.HOUR_OF_DAY):"0"+calendario.get(calendario.HOUR_OF_DAY);
        }
        minuto = calendario.get(calendario.MINUTE)>9?""+calendario.get(calendario.MINUTE):"0"+calendario.get(calendario.MINUTE);
        segundo = calendario.get(calendario.SECOND)>9?""+calendario.get(calendario.SECOND):"0"+calendario.get(calendario.SECOND);
    }
    
    public void setFieldsCliente(String nombre, String cedula, String direccion, String telefono){
        fieldNombre.setText(nombre);
        if (cedula.startsWith("")){
            comboNacional.setSelectedIndex(0);
        }
        if (cedula.startsWith("V")){
            comboNacional.setSelectedIndex(1);
        }
        if (cedula.startsWith("E")){
            comboNacional.setSelectedIndex(2);
        }
        if (cedula.startsWith("J")){
            comboNacional.setSelectedIndex(3);
        }
        fieldCI.setText(control.limpiarPalabra(cedula));
        fieldDireccion.setText(direccion);
        fieldTelefono.setText(telefono);
        if (!nombre.equals("")){
            fieldNombre.setEnabled(false);
            fieldDireccion.setEnabled(false);
            fieldTelefono.setEnabled(false); 
            fieldCI.setEnabled(false); 
            comboNacional.setEnabled(false);
            txtGuardar.setText("Eliminar");
        }
        else{
            fieldNombre.setEnabled(true);
            fieldDireccion.setEnabled(true);
            fieldTelefono.setEnabled(true); 
            comboNacional.setEnabled(true);
            fieldCI.setEnabled(true); 
            txtGuardar.setText("Buscar");
        }
    }
    
    public void setPrecios() throws ParseException{
        fieldTotalPagar.setText("");
        fieldIVA.setText("");
        fieldSubTotal.setText("");
        int i=0;
        float valor = 0;
        float valorAgregar =0;
        float IVA = 0;
        float subTotal = 0;
        
        while (i<tablaCaja.getRowCount()){
        valorAgregar = (Float.parseFloat(tablaCaja.getValueAt(i, 3).toString())*control.parseToFloat(tablaCaja.getValueAt(i, 5).toString()));
        valor = valor + valorAgregar; 
        
        fieldTotalPagar.setText(control.parseToString(valor));
        IVA = IVA + (valorAgregar * control.parseToFloat(tablaCaja.getValueAt(i, 4).toString())/100);
        fieldIVA.setText(control.parseToString(IVA));
        subTotal = valor - IVA;
        fieldSubTotal.setText(control.parseToString(subTotal));
        i++;
        
        }
        /*if(valor >= 10000000){
        long valorGrande;
        valorGrande = (long) valor;
        fieldTotalPagar.setText(Long.toString(valorGrande));
        }
        if(valor >= 10000000){
        long IVAGrande;
        IVAGrande = (long) IVA;
        fieldIVA.setText(Long.toString(IVAGrande));
        }
        if(subTotal >= 10000000){
        long subTotalGrande;
        subTotalGrande = (long) subTotal;
        fieldSubTotal.setText(Long.toString(subTotalGrande));
        }       */
        
    }
    
    public void cleanAll() throws ParseException{
            setFieldsCliente("","","","");
                   tablaCaja.setModel(control.removeRows((DefaultTableModel)tablaCaja.getModel()));
                   setPrecios();
                   fechaActual.setCalendar(null);
    }
    
    public void setVendido(){
        int i=0;
        while(i<tablaCaja.getRowCount()){
           String ID=tablaCaja.getValueAt(i,1).toString();
           String num=tablaCaja.getValueAt(i,3).toString();
           Inventarioxml.guardarCantidadVendida(ID, num);
           //System.out.println("Error");
           i++;
        }
        
    }
}
