/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Controlador.Controladora;
import Interfaz.menuArticulo;
import Interfaz.menuEditar;
import Interfaz.menuEditarRapido;
import Interfaz.menuEntrada;
import java.awt.Color;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import proyectoferreteria.Articulo;
import ClasesDocumentos.Documento;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.util.TimeZone;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.TableRowSorter;


/**
 *
 * @author VícAlex
 */
public class menuInventario extends javax.swing.JFrame implements Runnable {

    private String  hora,minuto,segundo,ampm,dia,mes,anio;
    private Calendar calendario;
    private Thread h1;
    private JPanel panel;
    private Documento xml;
    private JFrame obj;
    private Controladora control=new Controladora();;
    //Documento doc;
    
    public menuInventario() {
        xml = new Documento();
        initComponents();
        setLocationRelativeTo(null);
        h1 = new Thread(this);
        h1.start();
        tablaInventario. setModel(xml.cargarTablaArticulo());
        comboInventario.requestFocus();
        //fieldBuscar.setForeground(new Color(255,255,255,150));
    }
    
    public menuInventario(Documento xml) {
        this.xml = xml;
        initComponents();
        setLocationRelativeTo(null);
        h1 = new Thread(this);
        h1.start();
        //this.doc=doc;
        tablaInventario. setModel(xml.cargarTablaArticulo());
       // fieldBuscar.setForeground(new Color(255,255,255,150));
        comboInventario.requestFocus();
    }
    
    public void setXML(Documento xml){
        this.xml=xml;
    }
    
    public Documento getXML(){
        return xml;
    }

    public void actualizarLista(){
        tablaInventario.setModel(xml.cargarTablaArticulo());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new javax.swing.JPanel();
        panel2 = new javax.swing.JPanel();
        btnregresar = new javax.swing.JPanel();
        txtRegresar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaInventario = new javax.swing.JTable();
        btnArticulo = new javax.swing.JPanel();
        txtAgregarArticulo = new javax.swing.JLabel();
        fieldBuscar = new javax.swing.JTextField();
        comboInventario = new javax.swing.JComboBox<>();
        txtDatos = new javax.swing.JLabel();
        txtNombre = new javax.swing.JLabel();
        txtFamilia = new javax.swing.JLabel();
        txtCodigoBarras = new javax.swing.JLabel();
        txtVenta = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JLabel();
        txtCosto = new javax.swing.JLabel();
        txtExistencias = new javax.swing.JLabel();
        txtimpuestos = new javax.swing.JLabel();
        fieldNombre = new javax.swing.JTextField();
        fieldFamilia = new javax.swing.JTextField();
        fieldCodigoBarras = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        fieldDescripcion = new javax.swing.JTextArea();
        fieldCosto = new javax.swing.JTextField();
        fieldImpuesto = new javax.swing.JTextField();
        fieldVenta = new javax.swing.JTextField();
        fieldExitencias = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JPanel();
        txtEliminar = new javax.swing.JLabel();
        btnEditar = new javax.swing.JPanel();
        txtEditar = new javax.swing.JLabel();
        fieldID = new javax.swing.JTextField();
        txtID = new javax.swing.JLabel();
        btnEditarRapido = new javax.swing.JPanel();
        txtEditarRapido = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtLocal = new javax.swing.JLabel();
        txtReloj = new javax.swing.JLabel();
        txtFecha = new javax.swing.JLabel();
        txtInventario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        panel1.setBackground(new java.awt.Color(16, 135, 60));

        panel2.setBackground(new java.awt.Color(10, 91, 40));
        panel2.setAlignmentX(1.0F);
        panel2.setAlignmentY(1.0F);

        btnregresar.setBackground(new java.awt.Color(16, 135, 61));
        btnregresar.setPreferredSize(new java.awt.Dimension(96, 34));
        btnregresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnregresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnregresarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnregresarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnregresarMouseReleased(evt);
            }
        });
        btnregresar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtRegresar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtRegresar.setForeground(new java.awt.Color(255, 255, 255));
        txtRegresar.setText("Regresar");
        btnregresar.add(txtRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 30));

        tablaInventario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tablaInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "ID", "Familia", "Descripcion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaInventario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tablaInventarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tablaInventarioFocusLost(evt);
            }
        });
        tablaInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tablaInventarioMouseReleased(evt);
            }
        });
        tablaInventario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tablaInventarioKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tablaInventario);
        if (tablaInventario.getColumnModel().getColumnCount() > 0) {
            tablaInventario.getColumnModel().getColumn(0).setPreferredWidth(50);
            tablaInventario.getColumnModel().getColumn(1).setPreferredWidth(50);
            tablaInventario.getColumnModel().getColumn(2).setPreferredWidth(50);
            tablaInventario.getColumnModel().getColumn(3).setMinWidth(53);
            tablaInventario.getColumnModel().getColumn(3).setPreferredWidth(200);
        }

        btnArticulo.setBackground(new java.awt.Color(16, 135, 61));
        btnArticulo.setPreferredSize(new java.awt.Dimension(96, 34));
        btnArticulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnArticuloMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnArticuloMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnArticuloMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnArticuloMouseReleased(evt);
            }
        });
        btnArticulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtAgregarArticulo.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtAgregarArticulo.setForeground(new java.awt.Color(255, 255, 255));
        txtAgregarArticulo.setText("Agregar Articulo");
        btnArticulo.add(txtAgregarArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 130, 30));

        fieldBuscar.setBackground(new java.awt.Color(16, 135, 61));
        fieldBuscar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        fieldBuscar.setForeground(new java.awt.Color(255, 255, 255,150));
        fieldBuscar.setText("Buscar");
        fieldBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(35, 155, 81)));
        fieldBuscar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldBuscarFocusLost(evt);
            }
        });
        fieldBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                fieldBuscarMousePressed(evt);
            }
        });
        fieldBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fieldBuscarKeyReleased(evt);
            }
        });

        comboInventario.setBackground(new java.awt.Color(16, 135, 61));
        comboInventario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        comboInventario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre", "ID", "Familia" }));
        comboInventario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(35, 155, 81)));
        comboInventario.requestFocus();

        txtDatos.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        txtDatos.setForeground(new java.awt.Color(255, 255, 255));
        txtDatos.setText("Consultar Datos del Articulo");

        txtNombre.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(255, 255, 255));
        txtNombre.setText("Nombre:");

        txtFamilia.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtFamilia.setForeground(new java.awt.Color(255, 255, 255));
        txtFamilia.setText("Familia:");

        txtCodigoBarras.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtCodigoBarras.setForeground(new java.awt.Color(255, 255, 255));
        txtCodigoBarras.setText("C Barras:");

        txtVenta.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtVenta.setForeground(new java.awt.Color(255, 255, 255));
        txtVenta.setText("Venta:");

        txtDescripcion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        txtDescripcion.setText("Descripcion:");

        txtCosto.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtCosto.setForeground(new java.awt.Color(255, 255, 255));
        txtCosto.setText("Costo:");

        txtExistencias.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtExistencias.setForeground(new java.awt.Color(255, 255, 255));
        txtExistencias.setText("Existencias:");

        txtimpuestos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtimpuestos.setForeground(new java.awt.Color(255, 255, 255));
        txtimpuestos.setText("Impuestos:");

        fieldNombre.setEditable(false);
        fieldNombre.setBackground(new java.awt.Color(16, 135, 61));
        fieldNombre.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        fieldNombre.setForeground(new java.awt.Color(255, 255, 255));
        fieldNombre.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fieldNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(35, 155, 81)));
        fieldNombre.setCaretColor(new java.awt.Color(255, 255, 255));
        fieldNombre.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        fieldNombre.setMaximumSize(new java.awt.Dimension(2147, 2147));
        fieldNombre.setMinimumSize(new java.awt.Dimension(2, 21));
        fieldNombre.setPreferredSize(new java.awt.Dimension(2, 21));
        fieldNombre.setRequestFocusEnabled(false);

        fieldFamilia.setEditable(false);
        fieldFamilia.setBackground(new java.awt.Color(16, 135, 61));
        fieldFamilia.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        fieldFamilia.setForeground(new java.awt.Color(255, 255, 255));
        fieldFamilia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(35, 155, 81)));
        fieldFamilia.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        fieldFamilia.setPreferredSize(new java.awt.Dimension(2, 21));
        fieldFamilia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldFamiliaActionPerformed(evt);
            }
        });

        fieldCodigoBarras.setEditable(false);
        fieldCodigoBarras.setBackground(new java.awt.Color(16, 135, 61));
        fieldCodigoBarras.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        fieldCodigoBarras.setForeground(new java.awt.Color(255, 255, 255));
        fieldCodigoBarras.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(35, 155, 81)));
        fieldCodigoBarras.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        fieldCodigoBarras.setPreferredSize(new java.awt.Dimension(2, 21));

        jScrollPane2.setPreferredSize(new java.awt.Dimension(200, 40));

        fieldDescripcion.setEditable(false);
        fieldDescripcion.setBackground(new java.awt.Color(16, 135, 61));
        fieldDescripcion.setColumns(20);
        fieldDescripcion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        fieldDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        fieldDescripcion.setRows(5);
        fieldDescripcion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(35, 155, 81)));
        fieldDescripcion.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        fieldDescripcion.setPreferredSize(new java.awt.Dimension(242, 90));
        jScrollPane2.setViewportView(fieldDescripcion);

        fieldCosto.setEditable(false);
        fieldCosto.setBackground(new java.awt.Color(16, 135, 61));
        fieldCosto.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        fieldCosto.setForeground(new java.awt.Color(255, 255, 255));
        fieldCosto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(35, 155, 81)));
        fieldCosto.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        fieldCosto.setPreferredSize(new java.awt.Dimension(2, 21));
        fieldCosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCostoActionPerformed(evt);
            }
        });

        fieldImpuesto.setEditable(false);
        fieldImpuesto.setBackground(new java.awt.Color(16, 135, 61));
        fieldImpuesto.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        fieldImpuesto.setForeground(new java.awt.Color(255, 255, 255));
        fieldImpuesto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(35, 155, 81)));
        fieldImpuesto.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        fieldImpuesto.setPreferredSize(new java.awt.Dimension(2, 21));

        fieldVenta.setEditable(false);
        fieldVenta.setBackground(new java.awt.Color(16, 135, 61));
        fieldVenta.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        fieldVenta.setForeground(new java.awt.Color(255, 255, 255));
        fieldVenta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(35, 155, 81)));
        fieldVenta.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        fieldVenta.setPreferredSize(new java.awt.Dimension(2, 21));
        fieldVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldVentaActionPerformed(evt);
            }
        });

        fieldExitencias.setEditable(false);
        fieldExitencias.setBackground(new java.awt.Color(16, 135, 61));
        fieldExitencias.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        fieldExitencias.setForeground(new java.awt.Color(255, 255, 255));
        fieldExitencias.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(35, 155, 81)));
        fieldExitencias.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        fieldExitencias.setPreferredSize(new java.awt.Dimension(2, 21));

        btnEliminar.setBackground(new java.awt.Color(16, 135, 61));
        btnEliminar.setPreferredSize(new java.awt.Dimension(96, 34));
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEliminarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnEliminarMouseReleased(evt);
            }
        });
        btnEliminar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtEliminar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtEliminar.setForeground(new java.awt.Color(255, 255, 255));
        txtEliminar.setText("Eliminar");
        txtEliminar.setEnabled(false);
        btnEliminar.add(txtEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 70, 30));

        btnEditar.setBackground(new java.awt.Color(16, 135, 61));
        btnEditar.setPreferredSize(new java.awt.Dimension(96, 34));
        btnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEditarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnEditarMouseReleased(evt);
            }
        });
        btnEditar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtEditar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtEditar.setForeground(new java.awt.Color(255, 255, 255));
        txtEditar.setText("Editar");
        txtEditar.setEnabled(false);
        btnEditar.add(txtEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 50, 30));

        fieldID.setEditable(false);
        fieldID.setBackground(new java.awt.Color(16, 135, 61));
        fieldID.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        fieldID.setForeground(new java.awt.Color(255, 255, 255));
        fieldID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(35, 155, 81)));
        fieldID.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        fieldID.setPreferredSize(new java.awt.Dimension(2, 21));

        txtID.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtID.setForeground(new java.awt.Color(255, 255, 255));
        txtID.setText("Codigo ID:");

        btnEditarRapido.setBackground(new java.awt.Color(16, 135, 61));
        btnEditarRapido.setPreferredSize(new java.awt.Dimension(96, 34));
        btnEditarRapido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditarRapidoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditarRapidoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEditarRapidoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnEditarRapidoMouseReleased(evt);
            }
        });
        btnEditarRapido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtEditarRapido.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtEditarRapido.setForeground(new java.awt.Color(255, 255, 255));
        txtEditarRapido.setText("Edicion Rapida");
        btnEditarRapido.add(txtEditarRapido, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 120, 30));

        jLabel27.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Bs.");

        jLabel28.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("%");

        jLabel26.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Bs.");

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addComponent(fieldBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditarRapido, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                                .addComponent(btnregresar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                                .addComponent(txtDatos)
                                .addGap(40, 40, 40))))
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panel2Layout.createSequentialGroup()
                                    .addGap(55, 55, 55)
                                    .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtID, javax.swing.GroupLayout.Alignment.TRAILING)))
                                .addComponent(txtFamilia, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtCodigoBarras, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(txtCosto, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtimpuestos, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtVenta, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDescripcion, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtExistencias, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panel2Layout.createSequentialGroup()
                                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fieldImpuesto, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                                    .addComponent(fieldVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel27)))
                            .addComponent(jSeparator1)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fieldExitencias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fieldCodigoBarras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fieldFamilia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fieldID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fieldNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panel2Layout.createSequentialGroup()
                                .addComponent(fieldCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel26))
                            .addComponent(jSeparator2))
                        .addContainerGap(22, Short.MAX_VALUE))))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(comboInventario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDatos))
                .addGap(6, 6, 6)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEditarRapido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5))
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldFamilia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFamilia))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodigoBarras))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldExitencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtExistencias))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDescripcion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26)
                            .addComponent(txtCosto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28)
                            .addComponent(txtimpuestos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27)
                            .addComponent(txtVenta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btnregresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );

        txtLocal.setFont(new java.awt.Font("Arial Black", 2, 24)); // NOI18N
        txtLocal.setForeground(new java.awt.Color(255, 255, 255));
        txtLocal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ultrpequeño-05.png"))); // NOI18N
        txtLocal.setText("Ferreluso");
        txtLocal.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 2, new java.awt.Color(10, 91, 40)));

        txtReloj.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtReloj.setForeground(new java.awt.Color(255, 255, 255));
        txtReloj.setText("Reloj");

        txtFecha.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtFecha.setForeground(new java.awt.Color(255, 255, 255));
        txtFecha.setText("Fecha");

        txtInventario.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        txtInventario.setForeground(new java.awt.Color(255, 255, 255));
        txtInventario.setText("Inventario");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtInventario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 563, Short.MAX_VALUE)
                .addComponent(txtFecha)
                .addGap(18, 18, 18)
                .addComponent(txtReloj)
                .addGap(24, 24, 24))
            .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtInventario)
                    .addComponent(txtReloj)
                    .addComponent(txtFecha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnregresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnregresarMouseEntered
        //crea el borde del "boton"
        btnregresar.setBorder(BorderFactory.createMatteBorder(2, 2, 2, 2,Color.getHSBColor(143, 30, 77)));
    }//GEN-LAST:event_btnregresarMouseEntered

    private void btnregresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnregresarMouseExited
        // cuando el raton sale del boton
        btnregresar.setBorder(null);
    }//GEN-LAST:event_btnregresarMouseExited

    private void btnregresarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnregresarMousePressed
        // cuando se presiona el boton
        btnregresar.setBorder(null);
    }//GEN-LAST:event_btnregresarMousePressed

    private void btnregresarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnregresarMouseReleased
        // cuando se suelta el boton
        // Aqui se ejecuta el codigo del boton
        btnregresar.setBorder(BorderFactory.createMatteBorder(2, 2, 2, 2,Color.getHSBColor(143, 30, 77)));
        menuEntrada obj = new menuEntrada();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnregresarMouseReleased

    private void btnArticuloMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnArticuloMouseEntered
        //crea el borde del "boton"
        btnArticulo.setBorder(BorderFactory.createMatteBorder(2, 2, 2, 2,Color.getHSBColor(143, 30, 77)));
    }//GEN-LAST:event_btnArticuloMouseEntered

    private void btnArticuloMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnArticuloMouseExited
        // cuando el raton sale del boton
        btnArticulo.setBorder(null);
    }//GEN-LAST:event_btnArticuloMouseExited

    private void btnArticuloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnArticuloMousePressed
        // cuando se presiona el boton
        btnArticulo.setBorder(null);
    }//GEN-LAST:event_btnArticuloMousePressed

    private void btnArticuloMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnArticuloMouseReleased
        // cuando se suelta el boton
        // Aqui se ejecuta el codigo del boton
        btnArticulo.setBorder(BorderFactory.createMatteBorder(2, 2, 2, 2,Color.getHSBColor(143, 30, 77)));
        if(obj == null || !obj.isVisible()){   
            obj = new menuArticulo(this);
            obj.setVisible(true);
            setEnabled(false);
             
        }else
            obj.requestFocus();
    }//GEN-LAST:event_btnArticuloMouseReleased

    private void fieldCostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCostoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCostoActionPerformed

    private void btnEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseEntered
        //crea el borde del "boton"
        if (txtEliminar.isEnabled())
        btnEliminar.setBorder(BorderFactory.createMatteBorder(2, 2, 2, 2,Color.getHSBColor(143, 30, 77)));
    }//GEN-LAST:event_btnEliminarMouseEntered

    private void btnEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseExited
        // cuando el raton sale del boton
        btnEliminar.setBorder(null);
    }//GEN-LAST:event_btnEliminarMouseExited

    private void btnEliminarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMousePressed
        // cuando se presiona el boton
        btnEliminar.setBorder(null);
    }//GEN-LAST:event_btnEliminarMousePressed

    private void btnEliminarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseReleased
       // cuando se suelta el boton
        // Aqui se ejecuta el codigo del boton
        if (txtEliminar.isEnabled()){
        btnEliminar.setBorder(BorderFactory.createMatteBorder(2, 2, 2, 2,Color.getHSBColor(143, 30, 77)));
        int tableSeleccion = tablaInventario.getSelectedRow();
        
        try {
            int confirmacion = JOptionPane.showOptionDialog(
                null,"¿Desea eliminar este  Articulo?", "::::...Confirmación...:::",
                JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,null,null);
            
            if(tableSeleccion != -1 && confirmacion == 0)  {
               String CI = tablaInventario.getModel().getValueAt(tableSeleccion,1).toString();
               xml.eliminarArticulo(CI);
               tablaInventario. setModel(xml.cargarTablaArticulo());
               fieldNombre.setText("");
               fieldCodigoBarras.setText("");
               fieldCosto.setText("");
               fieldDescripcion.setText("");
               fieldExitencias.setText("");
               fieldFamilia.setText("");
               fieldID.setText("");
               fieldImpuesto.setText("");
               fieldVenta.setText("");
               JOptionPane.showMessageDialog(null," Se han eliminado los datos del articulo");
            }              
        
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error, no se puede borrar, articulo no encontrado","Error",2);
       }
        comboInventario.requestFocus();
        }
    }//GEN-LAST:event_btnEliminarMouseReleased

    private void btnEditarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseEntered
        //crea el borde del "boton"
        if (txtEliminar.isEnabled())
        btnEditar.setBorder(BorderFactory.createMatteBorder(2, 2, 2, 2,Color.getHSBColor(143, 30, 77)));
    }//GEN-LAST:event_btnEditarMouseEntered

    private void btnEditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseExited
        // cuando el raton sale del boton
        btnEditar.setBorder(null);
    }//GEN-LAST:event_btnEditarMouseExited

    private void btnEditarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMousePressed
        // cuando se presiona el boton
        btnEditar.setBorder(null);
    }//GEN-LAST:event_btnEditarMousePressed

    private void btnEditarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseReleased
        // cuando se suelta el boton
        // Aqui se ejecuta el codigo del boton
        if (txtEditar.isEnabled()){
        btnEditar.setBorder(BorderFactory.createMatteBorder(2, 2, 2, 2,Color.getHSBColor(143, 30, 77)));
        setEnabled(false);
        if(obj == null || !obj.isVisible()){ 
            
            
                String ID = tablaInventario.getModel().getValueAt(tablaInventario.getSelectedRow(),1).toString();
                obj = new menuEditar(this,ID);
                obj.setVisible(true);
                //comboInventario.requestFocus();
                
                
                //enable(false);
            }else
                JOptionPane.showMessageDialog(null, "Error seleccione un Articulo de la tabla para editar");
        
        }
        
    }//GEN-LAST:event_btnEditarMouseReleased

    private void fieldFamiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldFamiliaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldFamiliaActionPerformed

    private void btnEditarRapidoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarRapidoMouseEntered
        //crea el borde del "boton"
        btnEditarRapido.setBorder(BorderFactory.createMatteBorder(2, 2, 2, 2,Color.getHSBColor(143, 30, 77)));
    }//GEN-LAST:event_btnEditarRapidoMouseEntered

    private void btnEditarRapidoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarRapidoMouseExited
        // cuando el raton sale del boton
        btnEditarRapido.setBorder(null);
    }//GEN-LAST:event_btnEditarRapidoMouseExited

    private void btnEditarRapidoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarRapidoMousePressed
        // cuando se presiona el boton
        btnEditarRapido.setBorder(null);
    }//GEN-LAST:event_btnEditarRapidoMousePressed

    private void btnEditarRapidoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarRapidoMouseReleased
        // cuando se suelta el boton
        // Aqui se ejecuta el codigo del boton
        btnEditarRapido.setBorder(BorderFactory.createMatteBorder(2, 2, 2, 2,Color.getHSBColor(143, 30, 77)));
        if(obj == null || !obj.isVisible()){   
            obj = new menuEditarRapido(this);
            obj.setVisible(true);
            setEnabled(false);
             comboInventario.requestFocus();
            
        }
            
            
       
    }//GEN-LAST:event_btnEditarRapidoMouseReleased

    private void fieldVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldVentaActionPerformed

    private void tablaInventarioMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaInventarioMouseReleased
         int tableSeleccion = tablaInventario.getSelectedRow();
        //try {
            if(tableSeleccion != -1)  {
             try {
                 Articulo obj = xml.cargarDatosArticulo(tablaInventario.getModel().getValueAt(tableSeleccion,1).toString());
                 fieldNombre.setText(obj.getNombre());
                 fieldCodigoBarras.setText(obj.getCodigoBarras());
                 fieldCosto.setText(control.parseToString(obj.getCosto()));
                 fieldDescripcion.setText(obj.getDescripcion());
                 fieldExitencias.setText(String.valueOf(obj.getUnidades()));
                 fieldFamilia.setText(obj.getFamilia());
                 fieldID.setText(String.valueOf(obj.getID()));
                 fieldImpuesto.setText(control.parseToString(obj.getImpuesto()));
                 fieldVenta.setText(control.parseToString(obj.getPrecio()));
                 txtEditar.setEnabled(true);
                 txtEliminar.setEnabled(true);
             } catch (ParseException ex) {
                 Logger.getLogger(menuInventario.class.getName()).log(Level.SEVERE, null, ex);
             }
            }else{
               fieldNombre.setText("");
               fieldCodigoBarras.setText("");
               fieldCosto.setText("");
               fieldDescripcion.setText("");
               fieldExitencias.setText("");
               fieldFamilia.setText("");
               fieldID.setText("");
               fieldImpuesto.setText("");
               fieldVenta.setText("");
            }
            
       // }
        /*catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error, datos de Articulo no encontrados");
        }*/
        
    }//GEN-LAST:event_tablaInventarioMouseReleased

    private void tablaInventarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tablaInventarioFocusGained
        // TODO add your handling code here:
        if (tablaInventario.getSelectedRow()!=-1){
            txtEditar.setEnabled(true);
            txtEliminar.setEnabled(true);
        }
    }//GEN-LAST:event_tablaInventarioFocusGained

    private void tablaInventarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tablaInventarioFocusLost
        // TODO add your handling code here:
       actualizarLista();
        if (tablaInventario.getSelectedRow()==-1){    
            txtEditar.setEnabled(false);
            txtEliminar.setEnabled(false);
            fieldNombre.setText("");
               fieldCodigoBarras.setText("");
               fieldCosto.setText("");
               fieldDescripcion.setText("");
               fieldExitencias.setText("");
               fieldFamilia.setText("");
               fieldID.setText("");
               fieldImpuesto.setText("");
               fieldVenta.setText("");
        }
        
    }//GEN-LAST:event_tablaInventarioFocusLost

    private void fieldBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldBuscarKeyReleased
        // TODO add your handling code here:
        if("Buscar".equals(fieldBuscar.getText())){
            fieldBuscar.setText("");
            fieldBuscar.setForeground(new Color(255,255,255));
        }
        DefaultTableModel modelo;
        modelo = xml.filtrarTablaArticulo(fieldBuscar.getText(),
                                 comboInventario.getSelectedIndex(),1);
        tablaInventario.setModel(modelo);
        if(tablaInventario.getSelectedRow()==-1){
            txtEditar.setEnabled(false);
            txtEliminar.setEnabled(false);
            }
    }//GEN-LAST:event_fieldBuscarKeyReleased

    private void fieldBuscarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldBuscarMousePressed
        // TODO add your handling code here:
        if("Buscar".equals(fieldBuscar.getText())){
            fieldBuscar.setText("");
            fieldBuscar.setForeground(new Color(255,255,255));
        }
    }//GEN-LAST:event_fieldBuscarMousePressed

    private void fieldBuscarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldBuscarFocusLost
        // TODO add your handling code here:
        if (fieldBuscar.getText().equals("")){
            fieldBuscar.setForeground(new Color(255,255,255,150));
            fieldBuscar.setText("Buscar");
        }
            
    }//GEN-LAST:event_fieldBuscarFocusLost

    private void tablaInventarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaInventarioKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tablaInventarioKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
     

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuInventario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnArticulo;
    private javax.swing.JPanel btnEditar;
    private javax.swing.JPanel btnEditarRapido;
    private javax.swing.JPanel btnEliminar;
    private javax.swing.JPanel btnregresar;
    private javax.swing.JComboBox<String> comboInventario;
    private javax.swing.JTextField fieldBuscar;
    private javax.swing.JTextField fieldCodigoBarras;
    private javax.swing.JTextField fieldCosto;
    private javax.swing.JTextArea fieldDescripcion;
    private javax.swing.JTextField fieldExitencias;
    private javax.swing.JTextField fieldFamilia;
    private javax.swing.JTextField fieldID;
    private javax.swing.JTextField fieldImpuesto;
    private javax.swing.JTextField fieldNombre;
    private javax.swing.JTextField fieldVenta;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JTable tablaInventario;
    private javax.swing.JLabel txtAgregarArticulo;
    private javax.swing.JLabel txtCodigoBarras;
    private javax.swing.JLabel txtCosto;
    private javax.swing.JLabel txtDatos;
    private javax.swing.JLabel txtDescripcion;
    private javax.swing.JLabel txtEditar;
    private javax.swing.JLabel txtEditarRapido;
    private javax.swing.JLabel txtEliminar;
    private javax.swing.JLabel txtExistencias;
    private javax.swing.JLabel txtFamilia;
    private javax.swing.JLabel txtFecha;
    private javax.swing.JLabel txtID;
    private javax.swing.JLabel txtInventario;
    private javax.swing.JLabel txtLocal;
    private javax.swing.JLabel txtNombre;
    private javax.swing.JLabel txtRegresar;
    private javax.swing.JLabel txtReloj;
    private javax.swing.JLabel txtVenta;
    private javax.swing.JLabel txtimpuestos;
    // End of variables declaration//GEN-END:variables
@Override
    public void run() {
        Thread ct = Thread.currentThread();
        
        while(ct == h1){
            calcula();
            txtReloj.setText("Hora: "+hora+":"+minuto+":"+segundo+" "+ampm);
            txtFecha.setText("Fecha: "+dia+"/"+mes+"/"+anio);
            try{
                Thread.sleep(1000); 
                }
            catch(InterruptedException e){
            
            }
        }
    }

    private void calcula() {
        Calendar calendario = new GregorianCalendar();
        mes=(String) String.valueOf(calendario.get(Calendar.MONTH)+1);
        anio=(String) String.valueOf(calendario.get(Calendar.YEAR));
        dia=(String) String.valueOf(calendario.get(Calendar.DAY_OF_MONTH));
        //calendario.setTime(fechaHoraActual);
        ampm = calendario.get(Calendar.AM_PM) == calendario.AM?"AM":"PM";
        
        if(ampm.equals("PM")){
            int h = calendario.get(calendario.HOUR_OF_DAY)-12;
            h = h == 0?12:h;
            hora = h>9?""+h:"0"+h;
        }else{
            hora = calendario.get(calendario.HOUR_OF_DAY)>9?""+calendario.get(calendario.HOUR_OF_DAY):"0"+calendario.get(calendario.HOUR_OF_DAY);
        }
        minuto = calendario.get(calendario.MINUTE)>9?""+calendario.get(calendario.MINUTE):"0"+calendario.get(calendario.MINUTE);
        segundo = calendario.get(calendario.SECOND)>9?""+calendario.get(calendario.SECOND):"0"+calendario.get(calendario.SECOND);
    }
    
    
}
