/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import ClasesDocumentos.ImprecionPDF;
import Controlador.Controladora;

import ClasesDocumentos.Documento;
import ClasesDocumentos.FacturaDoc;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.text.ParseException;
import java.util.*;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import proyectoferreteria.Cliente;
import proyectoferreteria.Factura;
import proyectoferreteria.Venta;

public class menuEntrada extends javax.swing.JFrame implements Runnable {
   
    String  hora,minuto,segundo,ampm,dia,mes,anio;
    Thread h1;
    JPanel panel;
    Controladora control ;
    Documento doc;
    static ArrayList<Venta> ventas;
    static ArrayList<Factura> facturas;
    private static FacturaDoc xmlFactura;
    
    
    public menuEntrada() {
        
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        h1 = new Thread(this);
        h1.start();
        doc = new Documento(0);
        facturas=new ArrayList<>();
        xmlFactura=new FacturaDoc();
        try {
            facturas=xmlFactura.elementToArray();
        } catch (ParseException ex) {
            Logger.getLogger(menuEntrada.class.getName()).log(Level.SEVERE, null, ex);
        }
        menuRegistro.facturas=facturas;
        if (ventas!=null && !ventas.isEmpty()){
            labelNotificacion.setVisible(true);
            txtNotificacion.setText(Integer.toString(ventas.size()));
        }
       
       // ImageIcon imagen=new ImageIcon(getClass().getResource("/Imagenes/monitorIcon.png"));
       // Icon imagen1=new ImageIcon(imagen.getImage().getScaledInstance(40, 40, Image.SCALE_DEFAULT));
        //PCIcon.setIcon(imagen1);
    }
    
    public menuEntrada(ArrayList<Venta> ventas) {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        h1 = new Thread(this);
        h1.start();
        this.ventas=ventas;
        doc = new Documento(0);
        if (ventas!=null && !ventas.isEmpty()){
            labelNotificacion.setVisible(true);
            txtNotificacion.setText(Integer.toString(ventas.size()));
        }
        //ImageIcon imagen=new ImageIcon(getClass().getResource("/Imagenes/monitorIcon.png"));
        //Icon imagen1=new ImageIcon(imagen.getImage().getScaledInstance(40, 40, Image.SCALE_DEFAULT));
       
       
        
    }
    
    
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanel1 = new javax.swing.JPanel();
        panel2 = new javax.swing.JPanel();
        btnInventario = new javax.swing.JPanel();
        txtInventario = new javax.swing.JLabel();
        tablaIcon = new javax.swing.JLabel();
        btnCaja = new javax.swing.JPanel();
        txtNotificacion = new javax.swing.JLabel();
        labelNotificacion = new javax.swing.JLabel();
        txtCaja = new javax.swing.JLabel();
        PCIcon1 = new javax.swing.JLabel();
        btnRegistroContable = new javax.swing.JPanel();
        txtRegistroContable = new javax.swing.JLabel();
        LibroIcon = new javax.swing.JLabel();
        btnRegistro = new javax.swing.JPanel();
        txtRegistroCliente = new javax.swing.JLabel();
        personaIcon = new javax.swing.JLabel();
        txtReloj = new javax.swing.JLabel();
        txtFecha = new javax.swing.JLabel();
        txtSistema = new javax.swing.JLabel();
        btnSalir = new javax.swing.JPanel();
        txtSalir = new javax.swing.JLabel();
        powerIcon = new javax.swing.JLabel();
        txtLocal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(950, 540));
        setMinimumSize(new java.awt.Dimension(950, 540));
        setPreferredSize(new java.awt.Dimension(950, 540));

        jPanel1.setBackground(new java.awt.Color(16, 135, 60));
        jPanel1.setMaximumSize(new java.awt.Dimension(1000, 1000));
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 100));

        panel2.setBackground(new java.awt.Color(10, 91, 40));
        panel2.setAlignmentX(1.0F);
        panel2.setAlignmentY(1.0F);
        panel2.setMaximumSize(new java.awt.Dimension(1000, 10000));
        panel2.setPreferredSize(new java.awt.Dimension(100, 100));

        btnInventario.setBackground(new java.awt.Color(16, 135, 61));
        btnInventario.setPreferredSize(new java.awt.Dimension(96, 96));
        btnInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInventarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInventarioMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnInventarioMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnInventarioMouseReleased(evt);
            }
        });
        btnInventario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtInventario.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtInventario.setForeground(new java.awt.Color(255, 255, 255));
        txtInventario.setText("Inventario");
        btnInventario.add(txtInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        tablaIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carpetaIcon.png"))); // NOI18N
        btnInventario.add(tablaIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 10, 70, -1));

        btnCaja.setBackground(new java.awt.Color(16, 135, 61));
        btnCaja.setPreferredSize(new java.awt.Dimension(96, 96));
        btnCaja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCajaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnCajaMouseReleased(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCajaMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCajaMouseEntered(evt);
            }
        });
        btnCaja.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNotificacion.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        txtNotificacion.setForeground(new java.awt.Color(255, 255, 255));
        txtNotificacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNotificacion.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, txtNotificacion, org.jdesktop.beansbinding.ELProperty.create("Ventas en Espera"), txtNotificacion, org.jdesktop.beansbinding.BeanProperty.create("toolTipText"));
        bindingGroup.addBinding(binding);

        btnCaja.add(txtNotificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 40, 20));

        labelNotificacion.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        labelNotificacion.setForeground(new java.awt.Color(255, 255, 255));
        labelNotificacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNotificacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Punto.png"))); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, labelNotificacion, org.jdesktop.beansbinding.ELProperty.create("Ventas en Espera"), labelNotificacion, org.jdesktop.beansbinding.BeanProperty.create("toolTipText"));
        bindingGroup.addBinding(binding);

        labelNotificacion.setVisible(false);
        labelNotificacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelNotificacionMouseClicked(evt);
            }
        });
        btnCaja.add(labelNotificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 40, -1));

        txtCaja.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtCaja.setForeground(new java.awt.Color(255, 255, 255));
        txtCaja.setText("Caja");
        btnCaja.add(txtCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        PCIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/monitorIcon.png"))); // NOI18N
        btnCaja.add(PCIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 10, 70, -1));

        btnRegistroContable.setBackground(new java.awt.Color(16, 135, 61));
        btnRegistroContable.setPreferredSize(new java.awt.Dimension(96, 96));
        btnRegistroContable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegistroContableMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegistroContableMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnRegistroContableMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnRegistroContableMouseReleased(evt);
            }
        });
        btnRegistroContable.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtRegistroContable.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtRegistroContable.setForeground(new java.awt.Color(255, 255, 255));
        txtRegistroContable.setText("Registro Contable");
        btnRegistroContable.add(txtRegistroContable, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        LibroIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/libroIcon.png"))); // NOI18N
        btnRegistroContable.add(LibroIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 70, -1));

        btnRegistro.setBackground(new java.awt.Color(16, 135, 61));
        btnRegistro.setPreferredSize(new java.awt.Dimension(96, 96));
        btnRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnRegistroMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnRegistroMouseReleased(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegistroMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegistroMouseEntered(evt);
            }
        });
        btnRegistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtRegistroCliente.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtRegistroCliente.setForeground(new java.awt.Color(255, 255, 255));
        txtRegistroCliente.setText("Registro Clientes");
        btnRegistro.add(txtRegistroCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        personaIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/personaIcon.png"))); // NOI18N
        btnRegistro.add(personaIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 70, -1));

        txtReloj.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        txtReloj.setForeground(new java.awt.Color(255, 255, 255));
        txtReloj.setText("Reloj");

        txtFecha.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        txtFecha.setForeground(new java.awt.Color(255, 255, 255));
        txtFecha.setText("Fecha");

        txtSistema.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        txtSistema.setForeground(new java.awt.Color(255, 255, 255));
        txtSistema.setText("Sistema: Administrador");

        btnSalir.setBackground(new java.awt.Color(16, 135, 61));
        btnSalir.setPreferredSize(new java.awt.Dimension(96, 96));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalirMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSalirMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnSalirMouseReleased(evt);
            }
        });
        btnSalir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSalir.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtSalir.setForeground(new java.awt.Color(255, 255, 255));
        txtSalir.setText("Salir");
        btnSalir.add(txtSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        powerIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/powerIcon.png"))); // NOI18N
        btnSalir.add(powerIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 20, -1, 50));

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addComponent(btnCaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRegistroContable, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 206, Short.MAX_VALUE)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addComponent(txtSistema)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtFecha)
                        .addGap(18, 18, 18)
                        .addComponent(txtReloj)))
                .addGap(21, 21, 21))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistroContable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSistema)
                    .addComponent(txtReloj)
                    .addComponent(txtFecha))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        txtLocal.setFont(new java.awt.Font("Arial Black", 2, 36)); // NOI18N
        txtLocal.setForeground(new java.awt.Color(255, 255, 255));
        txtLocal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ferreluso hammer logo2-02.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(txtLocal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(txtLocal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInventarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInventarioMouseEntered
        //crea el borde del "boton"
        btnInventario.setBorder(BorderFactory.createMatteBorder(2, 2, 2, 2,Color.getHSBColor(143, 30, 77)));
    }//GEN-LAST:event_btnInventarioMouseEntered

    private void btnInventarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInventarioMouseExited
        // cuando el raton sale del boton
        btnInventario.setBorder(null);
    }//GEN-LAST:event_btnInventarioMouseExited

    private void btnInventarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInventarioMousePressed
        // cuando se presiona el boton
        btnInventario.setBorder(null);
    }//GEN-LAST:event_btnInventarioMousePressed

    private void btnInventarioMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInventarioMouseReleased
        // cuando se suelta el boton 
        // Aqui se ejecuta el codigo del boton
        btnInventario.setBorder(BorderFactory.createMatteBorder(2, 2, 2, 2,Color.getHSBColor(143, 30, 77)));
        menuInventario obj = new menuInventario();
        //doc = new Documento();
       // obj.setXml(doc);
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnInventarioMouseReleased

    private void btnCajaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCajaMouseEntered
        //crea el borde del "boton"
        btnCaja.setBorder(BorderFactory.createMatteBorder(2, 2, 2, 2,Color.getHSBColor(143, 30, 77)));
    }//GEN-LAST:event_btnCajaMouseEntered

    private void btnCajaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCajaMouseExited
        // cuando el raton sale del boton
        btnCaja.setBorder(null);
    }//GEN-LAST:event_btnCajaMouseExited

    private void btnCajaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCajaMousePressed
        // cuando se presiona el boton
        btnCaja.setBorder(null);
    }//GEN-LAST:event_btnCajaMousePressed

    private void btnCajaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCajaMouseReleased
        // cuando se suelta el boton
        // Aqui se ejecuta el codigo del boton
        btnCaja.setBorder(BorderFactory.createMatteBorder(2, 2, 2, 2,Color.getHSBColor(143, 30, 77)));
        if (ventas==null){
        menuCaja obj = new menuCaja();
        obj.setVisible(true);
        }else {
            menuCaja obj = new menuCaja(ventas);
            obj.setVisible(true);
        }
        
        dispose();
    }//GEN-LAST:event_btnCajaMouseReleased

    private void btnRegistroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistroMouseEntered
        //crea el borde del "boton"
        btnRegistro.setBorder(BorderFactory.createMatteBorder(2, 2, 2, 2,Color.getHSBColor(143, 30, 77)));
    }//GEN-LAST:event_btnRegistroMouseEntered

    private void btnRegistroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistroMouseExited
        // cuando el raton sale del boton
        btnRegistro.setBorder(null);
    }//GEN-LAST:event_btnRegistroMouseExited

    private void btnRegistroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistroMousePressed
        // cuando se presiona el boton
        btnRegistro.setBorder(null);
    }//GEN-LAST:event_btnRegistroMousePressed

    private void btnRegistroMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistroMouseReleased
        // cuando se suelta el boton
        // Aqui se ejecuta el codigo del boton
        btnRegistro.setBorder(BorderFactory.createMatteBorder(2, 2, 2, 2,Color.getHSBColor(143, 30, 77)));
        
        menuRegistroCliente obj = new menuRegistroCliente();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnRegistroMouseReleased

    private void btnSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseEntered
        //crea el borde del "boton"
        btnSalir.setBorder(BorderFactory.createMatteBorder(2, 2, 2, 2,Color.getHSBColor(143, 30, 77)));
    }//GEN-LAST:event_btnSalirMouseEntered

    private void btnSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseExited
        // cuando el raton sale del boton
        btnSalir.setBorder(null);
    }//GEN-LAST:event_btnSalirMouseExited

    private void btnSalirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMousePressed
        // cuando se presiona el boton
        btnSalir.setBorder(null);
    }//GEN-LAST:event_btnSalirMousePressed

    private void btnSalirMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseReleased
        // cuando se suelta el boton
        // Aqui se ejecuta el codigo del boton
        btnSalir.setBorder(BorderFactory.createMatteBorder(2, 2, 2, 2,Color.getHSBColor(143, 30, 77)));
        if(ventas==null || ventas.isEmpty()){
        int confirmacion = JOptionPane.showOptionDialog(
                        null,"¿Desea salir del sistema?", "::::...Confirmación...:::",
                        JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,null,null);
        if (confirmacion==0) {
            this.dispose();
            System.exit(1);
      } }
        else{
            int confirmacion=JOptionPane.showOptionDialog(
                        null,"Tiene ventas en espera ¿Seguro que desea salir del sistema?", "::::...Confirmación...:::",
                        JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,null,null);
        if (confirmacion==0) {
            this.dispose();
            System.exit(1);
      } 

        }
    }//GEN-LAST:event_btnSalirMouseReleased

    private void btnRegistroContableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistroContableMouseEntered
        //crea el borde del "boton"
        btnRegistroContable.setBorder(BorderFactory.createMatteBorder(2, 2, 2, 2,Color.getHSBColor(143, 30, 77)));
    }//GEN-LAST:event_btnRegistroContableMouseEntered

    private void btnRegistroContableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistroContableMouseExited
        // cuando el raton sale del boton
        btnRegistroContable.setBorder(null);
    }//GEN-LAST:event_btnRegistroContableMouseExited

    private void btnRegistroContableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistroContableMousePressed
        // cuando se presiona el boton
        btnRegistroContable.setBorder(null);
    }//GEN-LAST:event_btnRegistroContableMousePressed

    private void btnRegistroContableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistroContableMouseReleased
        try {
            // cuando se suelta el boton
            // Aqui se ejecuta el codigo del boton
            btnRegistroContable.setBorder(BorderFactory.createMatteBorder(2, 2, 2, 2,Color.getHSBColor(143, 30, 77)));
            menuRegistro obj=new menuRegistro();
            obj.setVisible(true);
            dispose();
        } catch (ParseException ex) {
            Logger.getLogger(menuEntrada.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRegistroContableMouseReleased

    private void labelNotificacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelNotificacionMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_labelNotificacionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuEntrada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LibroIcon;
    private javax.swing.JLabel PCIcon1;
    private javax.swing.JPanel btnCaja;
    private javax.swing.JPanel btnInventario;
    private javax.swing.JPanel btnRegistro;
    private javax.swing.JPanel btnRegistroContable;
    private javax.swing.JPanel btnSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelNotificacion;
    private javax.swing.JPanel panel2;
    private javax.swing.JLabel personaIcon;
    private javax.swing.JLabel powerIcon;
    private javax.swing.JLabel tablaIcon;
    private javax.swing.JLabel txtCaja;
    private javax.swing.JLabel txtFecha;
    private javax.swing.JLabel txtInventario;
    private javax.swing.JLabel txtLocal;
    private javax.swing.JLabel txtNotificacion;
    private javax.swing.JLabel txtRegistroCliente;
    private javax.swing.JLabel txtRegistroContable;
    private javax.swing.JLabel txtReloj;
    private javax.swing.JLabel txtSalir;
    private javax.swing.JLabel txtSistema;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
@Override
    public void run() {
        Thread ct = Thread.currentThread();
        
        while(ct == h1){
            calcula();
            txtReloj.setText("Hora: "+hora+":"+minuto+":"+segundo+" "+ampm);
            txtFecha.setText("Fecha: "+dia+"/"+mes+"/"+anio);
            try{
                Thread.sleep(1000); 
                }
            catch(InterruptedException e){
            
            }
        }

    }
    
    private void calcula() {
        Calendar calendario = new GregorianCalendar();
        mes=(String) String.valueOf(calendario.get(Calendar.MONTH)+1);
        anio=(String) String.valueOf(calendario.get(Calendar.YEAR));
        dia=(String) String.valueOf(calendario.get(Calendar.DAY_OF_MONTH));
        
        if(calendario.get(Calendar.AM_PM) == calendario.AM)
           ampm = "AM";
        else
           ampm = "PM";
           
        if(ampm.equals("PM")){
            int h = calendario.get(calendario.HOUR_OF_DAY)-12;
            h = h == 0?12:h;
            hora = h>9?""+h:"0"+h;
        }else
            hora = calendario.get(calendario.HOUR_OF_DAY)>9?""+calendario.get(calendario.HOUR_OF_DAY):"0"+calendario.get(calendario.HOUR_OF_DAY);
        minuto = calendario.get(calendario.MINUTE)>9?""+calendario.get(calendario.MINUTE):"0"+calendario.get(calendario.MINUTE);
        segundo = calendario.get(calendario.SECOND)>9?""+calendario.get(calendario.SECOND):"0"+calendario.get(calendario.SECOND);
    }
}
