/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Controlador.Controladora;
import ClasesDocumentos.Documento;
import java.awt.Color;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import proyectoferreteria.Articulo;

/**
 *
 * @author VícAlex
 */
public class menuBuscarArticulo extends javax.swing.JFrame {

    /* hacer codigo que permita detectar el articulo por defeto
    el cual sera un articulo editable en el momento de seleccionarlo*/
    
    Documento Inventarioxml;
    menuCaja ventana;
    Controladora control;
    
    public menuBuscarArticulo() {
        ventana = new menuCaja();
        initComponents();
        setLocationRelativeTo(null);
        Inventarioxml = new Documento(); 
    }
    
    public menuBuscarArticulo( menuCaja ventana) {
        initComponents();
        setLocationRelativeTo(null);
        Inventarioxml = new Documento(); 
        this.ventana=ventana;
        control = new Controladora();
        llenarTabla(Inventarioxml.cargarTablaArticuloCaja());
        comboBuscar.requestFocus();
        
        
        
    }
    
    public void llenarTabla(DefaultTableModel dataModel){
        tablaArticulo.setModel(dataModel);
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(JLabel.RIGHT);
        
        tablaArticulo.getColumnModel().getColumn(4).setCellRenderer(rightRenderer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtLocal = new javax.swing.JLabel();
        txtInventario = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        btnAgregarArticulo = new javax.swing.JPanel();
        txtAgregar = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JPanel();
        txtCAncelar = new javax.swing.JLabel();
        fieldBuscar = new javax.swing.JTextField();
        comboBuscar = new javax.swing.JComboBox<>();
        txtUnidades = new javax.swing.JLabel();
        txtNombre = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JLabel();
        fieldNombre = new javax.swing.JTextField();
        fieldID = new javax.swing.JTextField();
        fieldUnidades = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        fieldDescripcion = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaArticulo = new javax.swing.JTable();
        fieldPrecio = new javax.swing.JTextField();
        txtUnidades1 = new javax.swing.JLabel();
        txtBs = new javax.swing.JLabel();
        fieldIVA = new javax.swing.JTextField();
        txtIVA = new javax.swing.JLabel();
        txtPorcentaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(640, 540));
        setMinimumSize(new java.awt.Dimension(640, 540));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(16, 135, 60));
        jPanel1.setMaximumSize(new java.awt.Dimension(600, 500));
        jPanel1.setMinimumSize(new java.awt.Dimension(600, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(0, 0));
        jPanel1.requestFocus();

        txtLocal.setFont(new java.awt.Font("Arial Black", 2, 24)); // NOI18N
        txtLocal.setForeground(new java.awt.Color(255, 255, 255));
        txtLocal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ultrpequeño-05.png"))); // NOI18N
        txtLocal.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 2, new java.awt.Color(10, 91, 40)));

        txtInventario.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        txtInventario.setForeground(new java.awt.Color(255, 255, 255));
        txtInventario.setText("Articulo");

        jPanel2.setBackground(new java.awt.Color(10, 91, 40));
        jPanel2.setPreferredSize(new java.awt.Dimension(640, 540));

        jLabel16.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Seleccionar Articulo");

        btnAgregarArticulo.setBackground(new java.awt.Color(16, 135, 61));
        btnAgregarArticulo.setEnabled(false);
        btnAgregarArticulo.setPreferredSize(new java.awt.Dimension(96, 34));
        btnAgregarArticulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgregarArticuloMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgregarArticuloMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAgregarArticuloMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnAgregarArticuloMouseReleased(evt);
            }
        });
        btnAgregarArticulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtAgregar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtAgregar.setForeground(new java.awt.Color(255, 255, 255));
        txtAgregar.setText("Agregar");
        txtAgregar.setEnabled(false);
        btnAgregarArticulo.add(txtAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 30));

        btnCancelar.setBackground(new java.awt.Color(16, 135, 61));
        btnCancelar.setPreferredSize(new java.awt.Dimension(96, 34));
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCancelarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnCancelarMouseReleased(evt);
            }
        });
        btnCancelar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCAncelar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtCAncelar.setForeground(new java.awt.Color(255, 255, 255));
        txtCAncelar.setText("Finalizar");
        btnCancelar.add(txtCAncelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 70, 30));

        fieldBuscar.setBackground(new java.awt.Color(16, 135, 61));
        fieldBuscar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        fieldBuscar.setForeground(new java.awt.Color(255, 255, 255,150));
        fieldBuscar.setText("Buscar");
        fieldBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(35, 155, 81)));
        ;
        fieldBuscar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldBuscarFocusLost(evt);
            }
        });
        fieldBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                fieldBuscarMouseReleased(evt);
            }
        });
        fieldBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldBuscarActionPerformed(evt);
            }
        });
        fieldBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldBuscarKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fieldBuscarKeyReleased(evt);
            }
        });

        comboBuscar.setBackground(new java.awt.Color(16, 135, 61));
        comboBuscar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        comboBuscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre", "ID", "Familia", " " }));
        comboBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(35, 155, 81)));
        comboBuscar.requestFocus();
        comboBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBuscarActionPerformed(evt);
            }
        });

        txtUnidades.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtUnidades.setForeground(new java.awt.Color(255, 255, 255));
        txtUnidades.setText("Unidades:");

        txtNombre.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(255, 255, 255));
        txtNombre.setText("Nombre:");

        txtCodigo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtCodigo.setForeground(new java.awt.Color(255, 255, 255));
        txtCodigo.setText("Codigo ID:");

        txtDescripcion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        txtDescripcion.setText("Descripcion:");

        fieldNombre.setBackground(new java.awt.Color(16, 135, 61));
        fieldNombre.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        fieldNombre.setForeground(new java.awt.Color(255, 255, 255));
        fieldNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(35, 155, 81)));
        fieldNombre.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        fieldNombre.setEnabled(false);
        fieldNombre.requestFocus();
        fieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNombreActionPerformed(evt);
            }
        });

        fieldID.setBackground(new java.awt.Color(16, 135, 61));
        fieldID.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        fieldID.setForeground(new java.awt.Color(255, 255, 255));
        fieldID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(35, 155, 81)));
        fieldID.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        fieldID.setEnabled(false);
        fieldID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldIDActionPerformed(evt);
            }
        });

        fieldUnidades.setBackground(new java.awt.Color(16, 135, 61));
        fieldUnidades.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        fieldUnidades.setForeground(new java.awt.Color(255, 255, 255));
        fieldUnidades.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fieldUnidades.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(35, 155, 81)));
        fieldUnidades.setCaretColor(new java.awt.Color(255, 255, 255));
        fieldUnidades.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        fieldUnidades.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldUnidadesKeyTyped(evt);
            }
        });

        fieldDescripcion.setBackground(new java.awt.Color(16, 135, 61));
        fieldDescripcion.setColumns(20);
        fieldDescripcion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        fieldDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        fieldDescripcion.setRows(5);
        fieldDescripcion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(35, 155, 81)));
        fieldDescripcion.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        fieldDescripcion.setEnabled(false);
        jScrollPane2.setViewportView(fieldDescripcion);

        tablaArticulo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tablaArticulo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Codigo", "Familia", "Descripcion", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaArticulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tablaArticuloMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tablaArticulo);
        if (tablaArticulo.getColumnModel().getColumnCount() > 0) {
            tablaArticulo.getColumnModel().getColumn(0).setPreferredWidth(50);
            tablaArticulo.getColumnModel().getColumn(1).setPreferredWidth(50);
            tablaArticulo.getColumnModel().getColumn(2).setPreferredWidth(50);
            tablaArticulo.getColumnModel().getColumn(3).setPreferredWidth(200);
        }

        fieldPrecio.setBackground(new java.awt.Color(16, 135, 61));
        fieldPrecio.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        fieldPrecio.setForeground(new java.awt.Color(255, 255, 255));
        fieldPrecio.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        fieldPrecio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(35, 155, 81)));
        fieldPrecio.setCaretColor(new java.awt.Color(255, 255, 255));
        fieldPrecio.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        fieldPrecio.setEnabled(false);

        txtUnidades1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtUnidades1.setForeground(new java.awt.Color(255, 255, 255));
        txtUnidades1.setText("Precio:");

        txtBs.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtBs.setForeground(new java.awt.Color(255, 255, 255));
        txtBs.setText("Bs.");

        fieldIVA.setBackground(new java.awt.Color(16, 135, 61));
        fieldIVA.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        fieldIVA.setForeground(new java.awt.Color(255, 255, 255));
        fieldIVA.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        fieldIVA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(35, 155, 81)));
        fieldIVA.setCaretColor(new java.awt.Color(255, 255, 255));
        fieldIVA.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        fieldIVA.setEnabled(false);
        fieldIVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldIVAActionPerformed(evt);
            }
        });

        txtIVA.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtIVA.setForeground(new java.awt.Color(255, 255, 255));
        txtIVA.setText("IVA:");

        txtPorcentaje.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtPorcentaje.setForeground(new java.awt.Color(255, 255, 255));
        txtPorcentaje.setText("%");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(fieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel16))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap(50, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDescripcion, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtIVA, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtUnidades1, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(fieldIVA, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(fieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtBs)))
                                        .addGap(42, 42, 42)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtUnidades, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtCodigo, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(fieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fieldUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(fieldNombre)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAgregarArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(comboBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDescripcion)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIVA)
                            .addComponent(fieldIVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodigo)
                            .addComponent(fieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPorcentaje))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUnidades1)
                            .addComponent(fieldUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUnidades)
                            .addComponent(txtBs))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtInventario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(txtInventario))
                    .addComponent(txtLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarArticuloMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarArticuloMouseEntered
        //crea el borde del "boton"
        if (tablaArticulo.getSelectedRow()!=-1)
        btnAgregarArticulo.setBorder(BorderFactory.createMatteBorder(2, 2, 2, 2,Color.getHSBColor(143, 30, 77)));
    }//GEN-LAST:event_btnAgregarArticuloMouseEntered

    private void btnAgregarArticuloMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarArticuloMouseExited
        // cuando el raton sale del boton
        btnAgregarArticulo.setBorder(null);
    }//GEN-LAST:event_btnAgregarArticuloMouseExited

    private void btnAgregarArticuloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarArticuloMousePressed
        // cuando se presiona el boton
        btnAgregarArticulo.setBorder(null);
    }//GEN-LAST:event_btnAgregarArticuloMousePressed

    private void btnAgregarArticuloMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarArticuloMouseReleased
        // cuando se suelta el boton
        // Aqui se ejecuta el codigo del boton
        String Error = "";
        if( fieldNombre.getText().matches("^[ ]*"))
                Error = Error + "- El Articulo tiene que tener un nombre \n";
        float precio = 0;
        try{
            precio= control.parseToFloat(fieldPrecio.getText());
        }
        catch(NumberFormatException e){
            Error = Error + "- El precio de venta no es valido \n";
        } catch (ParseException ex) {
            Logger.getLogger(menuBuscarArticulo.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        int unidades = 0;
        if("".equals(fieldUnidades.getText())){
            Error = Error + "- Debe definir las unidades a vender del articulo seleccionado\n";
        }
        else try{
            unidades= Integer.parseInt(fieldUnidades.getText());
        }
        catch(NumberFormatException e){
            Error = Error + "- El numero de unidades no es valido \n";
        }
        
        try{
            float impuesto = control.parseToFloat(fieldIVA.getText());
            
            if(impuesto > 100.0 || impuesto < 0.0)
                Error = Error + "- Impuesto Fuera de rango( 0% - 100% ) \n";
        }catch(NumberFormatException e){
            Error = Error + "- Valor de impuesto no es vlido \n";
        } catch (ParseException ex) {
            Logger.getLogger(menuBuscarArticulo.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if("".equals(Error)){
            if (tablaArticulo.getSelectedRow()!=-1 && txtAgregar.isEnabled()){
                if (!control.checkTable(ventana.getTablaCaja(), fieldID.getText(),fieldUnidades.getText())){
                control.agregarArticulo(ventana.getTablaCaja(), fieldNombre.getText(), fieldID.getText(),
                                        fieldDescripcion.getText(),fieldIVA.getText(), fieldPrecio.getText(), fieldUnidades.getText());
                btnAgregarArticulo.setBorder(BorderFactory.createMatteBorder(2, 2, 2, 2,Color.getHSBColor(143, 30, 77)));
                }
                try {
                    ventana.setPrecios();
                } catch (ParseException ex) {
                    Logger.getLogger(menuBuscarArticulo.class.getName()).log(Level.SEVERE, null, ex);
                }
        
            }
            
        }
        else
            JOptionPane.showMessageDialog(null,"Error:" + Error);
    }//GEN-LAST:event_btnAgregarArticuloMouseReleased

    private void btnCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseEntered
        //crea el borde del "boton"
        btnCancelar.setBorder(BorderFactory.createMatteBorder(2, 2, 2, 2,Color.getHSBColor(143, 30, 77)));
    }//GEN-LAST:event_btnCancelarMouseEntered

    private void btnCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseExited
        // cuando el raton sale del boton
        btnCancelar.setBorder(null);
    }//GEN-LAST:event_btnCancelarMouseExited

    private void btnCancelarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMousePressed
        // cuando se presiona el boton
        btnCancelar.setBorder(null);
    }//GEN-LAST:event_btnCancelarMousePressed

    private void btnCancelarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseReleased
        // cuando se suelta el boton
        // Aqui se ejecuta el codigo del boton
        btnCancelar.setBorder(BorderFactory.createMatteBorder(2, 2, 2, 2,Color.getHSBColor(143, 30, 77)));
        ventana.setEnabled(true);
        dispose();
        
    }//GEN-LAST:event_btnCancelarMouseReleased

    private void fieldBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldBuscarActionPerformed

    private void fieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNombreActionPerformed
    //agrega el articulo a la lista a vender
    private void tablaArticuloMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaArticuloMouseReleased
        try{
            //bloquea las casilla no editables
            if(fieldNombre.isEditable()) {
                fieldNombre.setEnabled(false);
                fieldID.setEnabled(false);
                fieldDescripcion.setEnabled(false);
                fieldPrecio.setEnabled(false);
                fieldIVA.setEnabled(false);
            }
            
            //busca el articulo y carga si informacion
            if (tablaArticulo.getSelectedRow()!=-1){
                btnAgregarArticulo.setEnabled(true);
                txtAgregar.setEnabled(true);
                Articulo e = control.agregarArticulo(tablaArticulo, Inventarioxml);
                fieldNombre.setText(e.getNombre());
                fieldID.setText(Integer.toString(e.getID()));
                fieldDescripcion.setText(e.getDescripcion());
                fieldPrecio.setText(control.parseToString(e.getPrecio()));
                fieldIVA.setText(control.parseToString(e.getImpuesto()));
                fieldUnidades.setText("");
                //articulo especial para momentos en los que no se ha agregado aun
                //un articulo al sistema
                if("Nuevo Articulo".equals(e.getNombre())){
                    fieldNombre.setEnabled(true);
                    fieldNombre.setText("");
                    fieldDescripcion.setEnabled(true);
                    fieldPrecio.setEnabled(true);
                    fieldPrecio.setText("");
                    fieldIVA.setEnabled(true);
                    fieldIVA.setText("");
                    
                }
            }
            else{
                txtAgregar.setEnabled(false);
                fieldNombre.setText("");
                fieldID.setText("");
                fieldDescripcion.setText("");
                fieldPrecio.setText("");
                fieldUnidades.setText("");
                fieldIVA.setText("");
            }

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error, datos de Articulo no encontrados");
            btnAgregarArticulo.setEnabled(false);
            txtAgregar.setEnabled(false);
            fieldNombre.setText("");
            fieldID.setText("");
            fieldDescripcion.setText("");
            fieldPrecio.setText("");
            fieldUnidades.setText("");
            fieldIVA.setText("");
        }
        
    }//GEN-LAST:event_tablaArticuloMouseReleased

    private void fieldBuscarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldBuscarMouseReleased
        // TODO add your handling code here:
        if (fieldBuscar.getText().equals("Buscar")){
            fieldBuscar.setForeground(new Color(255,255,255));
            fieldBuscar.setText("");
        }
    }//GEN-LAST:event_fieldBuscarMouseReleased

    private void fieldBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldBuscarKeyTyped
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_fieldBuscarKeyTyped

    private void fieldUnidadesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldUnidadesKeyTyped
        // TODO add your handling code here:
        control.validaNumero(evt);
    }//GEN-LAST:event_fieldUnidadesKeyTyped

    private void fieldIVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldIVAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldIVAActionPerformed

    private void fieldIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldIDActionPerformed

    private void fieldBuscarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldBuscarFocusLost
        // TODO add your handling code here:
         if (fieldBuscar.getText().equals("")){
            fieldBuscar.setForeground(new Color(255,255,255,150));
            fieldBuscar.setText("Buscar");
        }
    }//GEN-LAST:event_fieldBuscarFocusLost

    private void comboBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBuscarActionPerformed

    private void fieldBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldBuscarKeyReleased
        // TODO add your handling code here:
           DefaultTableModel modelo;
        JTable carga = new JTable();
        carga.setModel(Inventarioxml.cargarTablaArticuloCaja());
    modelo = control.filtrarTablaArticuloCaja(carga, 
                fieldBuscar.getText(), comboBuscar.getSelectedIndex());
      
        llenarTabla(modelo); 
    }//GEN-LAST:event_fieldBuscarKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuBuscarArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuBuscarArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuBuscarArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuBuscarArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuBuscarArticulo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnAgregarArticulo;
    private javax.swing.JPanel btnCancelar;
    private javax.swing.JComboBox<String> comboBuscar;
    private javax.swing.JTextField fieldBuscar;
    private javax.swing.JTextArea fieldDescripcion;
    private javax.swing.JTextField fieldID;
    private javax.swing.JTextField fieldIVA;
    private javax.swing.JTextField fieldNombre;
    private javax.swing.JTextField fieldPrecio;
    private javax.swing.JTextField fieldUnidades;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaArticulo;
    private javax.swing.JLabel txtAgregar;
    private javax.swing.JLabel txtBs;
    private javax.swing.JLabel txtCAncelar;
    private javax.swing.JLabel txtCodigo;
    private javax.swing.JLabel txtDescripcion;
    private javax.swing.JLabel txtIVA;
    private javax.swing.JLabel txtInventario;
    private javax.swing.JLabel txtLocal;
    private javax.swing.JLabel txtNombre;
    private javax.swing.JLabel txtPorcentaje;
    private javax.swing.JLabel txtUnidades;
    private javax.swing.JLabel txtUnidades1;
    // End of variables declaration//GEN-END:variables

   
    
    
}
